(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 200,
	height: 300,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/nespresso_atlas_.png?1471828720488", id:"nespresso_atlas_"}
	]
};



lib.ssMetadata = [
		{name:"nespresso_atlas_", frames: [[242,0,216,143],[376,145,113,112],[198,402,139,89],[0,402,196,105],[0,0,240,400],[376,259,94,71],[242,145,132,188],[339,375,66,66],[242,335,215,38]]}
];


// symbols:



(lib.BTS2016OFFER = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.Capsule = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.cloud1 = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.cloud2 = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.compos = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.hand = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.Machine = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.monogramm = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.nespresso_logo = function() {
	this.spriteSheet = ss["nespresso_atlas_"];
	this.gotoAndStop(8);
}).prototype = p = new cjs.Sprite();



(lib.Анимация21 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGpESQgHgEgFgEQgHgHgDgLQgFgLAAgOQAAgQAEgMQADgMAIgKQAGgIAMgFQAKgFAPAAIAIAAIAFACIAAAOIAAAAIgHgCIgJAAQgRAAgKAKQgJAKgCASQAHgDAGgCQAGgDAIAAQAIAAAGABQAFACAGAEQAHAFADAHQAEAHAAALQAAARgMAMQgMALgRAAQgIAAgHgCgAGqDWQgFABgGADIgBAEIAAAEQABAMACAHQACAHAFAFQADADAFABQAEACAFAAQALAAAGgGQAHgIAAgNQAAgHgCgFQgCgEgFgEQgDgDgFAAIgJgBQgHAAgGACgADOEFQgLgPABgfQgBgeALgQQAJgOAVAAQAVAAAKAPQAJAPAAAeQAAAfgJAPQgLAPgUAAQgVAAgJgPgADgCrQgFADgDAGQgDAGAAAJIgBAUIABAVQAAAIADAGQADAGAFAEQAEADAIAAQAHAAAFgDQAFgDACgGQAEgGABgJIABgVIgBgUQgBgJgEgGQgCgGgFgDQgFgEgHABQgHgBgFAEgAgvEUIgHgCIAAgPIABAAIAHACIAJABQARAAAKgKQAJgLABgSQgGAFgHACQgGACgHAAQgIgBgGgBQgFgCgHgEQgGgEgEgHQgDgIAAgKQAAgSAMgLQALgLARAAQAIAAAIADQAHACADAGQAHAGADAKQAEAKAAAQQAAAPgEANQgDANgHAIQgFAJgLAFQgLAFgOAAgAgrCvQgGAGgBAOQAAAHADAEQACAFAFAEQADACAEABIAKAAIANgBQAFgBAFgDIAAgEIAAgEQAAgMgBgHQgCgIgFgEQgEgDgEgCQgEgCgFABQgLgBgHAIgAibEFQgKgPAAgfQAAgeAKgQQAJgOAVAAQAWAAAJAPQAKAPgBAeQABAfgKAPQgKAPgVAAQgVAAgJgPgAiICrQgGADgCAGQgDAGgBAJIgBAUIABAVQABAIADAGQACAGAFAEQAEADAIAAQAIAAAEgDQAFgDADgGQADgGABgJIABgVIgBgUQgBgJgDgGQgDgGgFgDQgEgEgIABQgHgBgEAEgAk6ELQgLgLAAgPQgBgKAGgHQAGgIAKgEIAAgBQgKgFgEgGQgEgGgBgJQAAgNALgJQALgIARgBQASAAAJAJQALAIAAANQAAAIgFAHQgFAIgKAFIAAAAQAMAFAFAGQAGAIAAAKQAAAPgLAKQgMAKgSAAQgTAAgLgJgAkxDhQgEAHgBAIQABALAGAHQAIAGALABQAMgBAGgFQAHgGAAgLQAAgGgDgFQgDgFgKgDIgTgIQgHAEgEAGgAktCqQgFAFAAAJQAAAFACAEQADAEAHADIATAIQAHgGADgFQAEgGAAgGQAAgJgHgFQgGgFgKAAQgKAAgHAEgAo7EHQgKgMAAgVQAAgVAKgNQAMgMASAAQATAAAKAMQAMANgBAVQABAVgMAMQgKANgTAAQgSAAgMgNgAovDNQgHAIAAARQAAAQAHAJQAGAJAMgBQAMABAHgJQAGgJAAgQQAAgRgGgIQgHgIgMgBQgMABgGAIgAE0ESIAAgNIAYAAIAAhNIgYAAIAAgLIALgBIAIgCQAEgCACgDQACgDAAgFIANAAIAABoIAXAAIAAANgABgESIAAgRIAggcQAPgPAGgIQAFgIAAgLQAAgIgGgGQgGgEgKAAQgIgBgIADQgJADgHAFIgBAAIAAgRIAPgFQAJgCAJAAQASAAAKAIQAKAJAAAPQAAAGgBAGIgGALIgHAKIgrAoIA+AAIAAAOgAAtESIAAgXIATAAIAAAXgAjWESIAAgXIATAAIAAAXgAmfESIAAgNIAYAAIAAhNIgYAAIAAgLIALgBIAJgCQADgCACgDQACgDABgFIALAAIAABoIAYAAIAAANgApqESIAAhLIgsAAIAABLIgOAAIAAhYIBJAAIAABYgAE4A7QgIgDgFgFQgHgGgDgLQgEgLAAgPQAAgOADgLQAEgMAHgKQAHgJALgFQAKgEAPAAIAIAAIAGACIAAAOIAAAAIgHgCIgJgBQgRAAgKAKQgKALgBASQAGgEAHgCQAFgDAJAAQAIAAAFACQAGABAFAEQAIAGADAFQADAHABALQAAARgMAMQgMALgRgBQgJAAgGgCgAE5AAQgFABgGADIgBADIAAAEQAAANADAHQACAHAFAEQADAEAEABQAFACAEAAQALAAAHgHQAGgHAAgNQAAgHgBgFQgDgFgFgEQgDgBgFAAIgJAAQgGgBgGABgABcAuQgKgPAAgeQAAgdAKgPQAJgOAWAAQAUAAAKAOQAJAQAAAcQAAAfgJAPQgKAPgUgBQgWAAgJgPgABugqQgEAEgEAFQgCAGgBAKIgBASIABAVQABAHACAHQADAGAFADQAEADAJABQAHgBAFgDQAEgCADgHQADgGABgIIABgVIgBgTQgBgIgDgHQgDgFgEgEQgFgDgHAAQgIAAgFADgAinA0QgLgKAAgPQAAgKAGgIQAGgHAJgDIAAAAQgJgGgEgFQgFgGAAgJQAAgNALgJQAKgJASAAQARAAAKAIQALAJAAANQAAAHgGAIQgEAIgKAEIAAABQALACAGAHQAGAHgBAKQAAAPgLALQgMAKgRgBQgUAAgLgJgAieALQgEAGAAAJQAAALAHAGQAIAHALAAQALAAAHgGQAHgFgBgLQAAgHgDgFQgCgEgKgEIgTgIQgIAFgEAGgAiZgqQgGAFAAAIQAAAFADAFQADAEAHADIATAHQAHgFADgGQADgFAAgHQAAgIgGgGQgHgEgJAAQgKgBgHAFgAkNAuQgKgPABgeQgBgdAKgPQAKgOAVAAQAVAAAKAOQAJAQAAAcQAAAfgJAPQgLAPgUgBQgVAAgKgPgAj6gqQgFAEgDAFQgDAGAAAKIgBASIABAVQAAAHADAHQADAGAEADQAFADAIABQAHgBAFgDQAFgCADgHQADgGAAgIIABgVIgBgTQAAgIgDgHQgDgFgFgEQgFgDgHAAQgIAAgEADgAmmA9IgHgBIAAgQIABAAIAHADIAJABQARAAAKgLQAKgKABgSQgHAEgGACQgHACgHAAQgHAAgGgBQgGgCgGgEQgGgFgEgFQgDgHgBgKQAAgSAMgLQAMgLAQAAQAJAAAHACQAIADAFAFQAHAHADAKQADAJAAARQAAANgDANQgEAMgGAJQgIAJgKAEQgLAGgOgBgAmhgmQgHAHAAANQAAAHACAFQACAEAGACQADACAEACIAKAAIAMgCQAGgBAFgBIABgDIAAgFQAAgMgDgHQgCgHgFgEQgDgEgFgCQgDgBgGAAQgLAAgGAHgAqRA6QgIgCgGgGQgFgGgEgJQgDgIAAgLQAAgUAMgMQALgMAVAAQAHgBAHADIAOAFIAAAQIgBAAQgHgFgIgDQgGgCgHgBQgNAAgIAJQgGAHAAAQQAAAPAGAJQAIAIANAAIAJgBIAJgDIAKgHIABAAIAAAQQgJAFgHACIgMABQgKAAgIgDgADDA7IAAgMIAYAAIAAhMIgYAAIAAgKIALgBIAIgDQAEgCABgCQADgEAAgEIAMAAIAABmIAYAAIAAAMgAgQA7IAAgQIAfgcQAPgPAFgHQAGgIAAgKQgBgJgFgFQgHgFgKAAQgHAAgJACQgGADgHAFIgCAAIAAgRIANgEQAKgCAIAAQASgBAKAJQAKAJAAAOQAAAHgBAFIgFAMIgHAHIgrAoIA+AAIAAAOgAhCA7IAAgXIATAAIAAAXgAlHA7IAAgXIATAAIAAAXgAoRA7IAAgMIAZAAIAAhMIgZAAIAAgKIALgBIAJgDQAEgCACgCQACgEAAgEIAMAAIAABmIAXAAIAAAMgAG+h6IAPgkIgihTIAPAAIAbBBIAbhBIAQAAIgzB3gAgziFIAAgUIhBAAIAAAUIgPAAIAAghIAKAAQAKgPAEgUQAFgTgBgVIA3AAIAABLIALAAIAAAhgAhfjAQgFAPgHALIAtAAIAAg+IgbAAQgBATgFARgAmUiFIAAgUIhFAAIAAhYIAPAAIAABLIArAAIAAhLIAOAAIAABLIALAAIAAAhgAIZijQgMgMAAgWQAAgVAMgNQALgMATAAQASAAAJAKQAKAKAAATIAAAIIhAAAQAAAIACAHQACAFAFAEQAEAEAFACQAGACAGAAQAKAAAIgEQAKgDAEgEIAAAAIAAAQQgHAEgIACQgHABgJAAQgWAAgMgLgAJOjPQAAgLgGgHQgGgGgLAAQgNAAgGAHQgIAHAAAKIAyAAIAAAAgADFiaQgIgDgGgFQgFgHgEgIQgDgJAAgLQAAgVAMgNQALgMAVAAQAHAAAIACIANAGIAAAQIgBAAQgHgFgIgDQgGgDgHAAQgNAAgHAIQgIAJABAQQgBAQAIAIQAGAJAOAAIAJgBIAJgEIAKgGIABAAIAAAQQgJAEgHACQgGACgGgBQgKAAgIgCgAgLijQgMgMgBgWQAAgVAMgNQALgMASAAQASAAAJAKQAKAKAAATIAAAIIg/AAQAAAIACAHQADAFAEAEQACAEAGACQAFACAHAAQAJAAAJgEQAJgDAEgEIABAAIAAAQQgHAEgJACQgHABgJAAQgUAAgLgLgAAnjPQAAgLgFgHQgHgGgLAAQgMAAgFAHQgHAHgBAKIAwAAIAAAAgAKEiZIAAhLIggAAIAAgNIBOAAIAAANIggAAIAABLgAFWiZIAAhYIAwABQAFABAEACQAFACACAEQADAFAAAFQAAAHgEAFQgEAFgGACIAAABQAJABAEAGQAGAFgBAJQAAAHgCAEQgCAGgFACQgFAEgGACQgGABgKABgAFkilIAcgBQAEgBAEgCQADgCABgCQACgDAAgEQAAgEgBgDQgCgDgEgCIgGgCIgdAAgAFkjNIAbgBIAFgBQADgCACgDIABgGIgBgGQgBAAAAgBQAAAAgBgBQAAAAgBAAQAAgBgBAAIgIgCIgZAAgAEYiZIAAhLIgfAAIAAgNIBNAAIAAANIgfAAIAABLgACHiZIAAhCIguBCIgOAAIAAhYIAPAAIAABBIAthBIAOAAIAABYgAjXiZIAAgjIgSAAIgbAjIgSAAIAegkQgLgDgGgHQgEgGAAgLQAAgHACgFQADgEAFgDQAFgDAGgCQAGgBAIAAIAhAAIAABYgAjzjkQgDAAgDACQgDABgBADQgBADAAADIABAIQAAACADACIAHAEIAKABIASAAIAAgegAk3iZIAAhCIguBCIgNAAIAAhYIAOAAIAABBIAthBIAPAAIAABYgAn8iZIglgpIgHAAIAAApIgPAAIAAhYIAPAAIAAAmQAHAAAFgDQAEgDADgFIAEgJQAEgJAGgEQAHgFALAAIAHAAIAAANIgHAAQgGAAgEADQgDACgDAHQgDAHgDADQgEAEgDACIApAvgApYiZIgLghIgzAAIgMAhIgPAAIAqh1IAVAAIAqB1gAppjHIgUg6IgUA6IAoAAgABdkBQgHgHAAgLIANAAQAAAIAEAEQAEADAGAAQAHAAAEgDQADgEAAgIIAOAAQgBALgGAHQgIAGgNAAQgNAAgHgGg");
	this.shape.setTransform(0,10.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-69,-17.2,138.1,55.3);


(lib.Анимация20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.monogramm();
	this.instance.setTransform(-23,-13,0.7,0.7);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-23,-13,46.2,46.2);


(lib.Анимация19 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AvnXbMAAAgu2IfOAAMAAAAu2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-150,200,300);


(lib.Анимация18 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhkCUIAAknIA1AAIAAD3ICUAAIAAAwg");
	this.shape.setTransform(73.5,2.6,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZCUIAAknIAzAAIAAEng");
	this.shape_1.setTransform(63.5,2.6,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrCUQgtgKgfgdIAhgoQATAUAbAKQAaAJAagBQAYgBAPgJQAUgMgEgVQgCgTgbgLIgrgLQglgJgQgHQgegKgNgVQgSgfANgkQANgjAigOQAogRA0AJQAvAHAgAgIgfAnQgZgagkgGQgpgIgZAQQgOAKACAQQAAAPAOAJQALAIATAFIAeAHQAvAMAXAOQAgAWACAmIAAADQAAAjgYAXQgVAVgkAFQgUAEgTAAQgWAAgVgFg");
	this.shape_2.setTransform(53.3,2.5,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABgCUIgXg1IiSAAIgVA1Ig7AAIB9knIA7AAIB6EngAA1AwIg1iCIAAAAIg2CCIBrAAg");
	this.shape_3.setTransform(40,2.6,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA+CUIhGhaIhCAAIAABaIg1AAIAAknICGAAQAmABAbASQAeAVAIAiQAJAngPAiQgQAkgkAOIBMBigAhKALIBKAAQAaAAAQgOQARgRAAgZQAAgZgRgOQgQgPgaAAIhKAAg");
	this.shape_4.setTransform(26.1,2.6,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah3CTIAAklICDAAQAdAAAWAKQAaAMAJAYQAKAbgKAaQgLAagbALQAhAIARAaQARAcgKAiQgIAegfARQgaAOgjAAgAhBBmIBNAAQAWABAPgLQARgNABgUQABgWgQgMQgOgNgXAAIhQAAgAhDgdIBLAAQARAAALgJQAMgKAAgQQABgTgMgKQgMgKgSAAIhKAAg");
	this.shape_5.setTransform(11.9,2.6,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGByQgpgCgbgYQgagWgJglQgIgiALgiQALgjAfgUQAdgUAkAAQAqAAAfAZQAfAaAGApQAHAigMAhQgNAjgeASQgbARgiAAIgIgBgAgChGQgXACgPAOQgPAPgEAXQgEATAGAVQAGAVAQAMQAQANAUAAQAYAAASgRQAQgPAFgaQADgTgHgUQgHgWgRgMQgPgJgTAAIgEAAg");
	this.shape_6.setTransform(-8.1,4.2,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqCRQgvgQgQg2QgOgyAUgsQAKgWASgPQASgPAXgEQAcgFAXAIQAcAJANAXIAAhtIAyAAIAAElIgxAAIAAggIgBAAQgPAaggAIQgNAEgMAAQgQAAgQgFgAg0AEQgSAoAWAjQAKASAUAHQASAGATgFQAUgGAMgQQALgRAAgUIAAgUQAAgYgQgQQgQgSgYgBIgGAAQgkAAgQAlg");
	this.shape_7.setTransform(-20.9,2.7,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABOB9IibjJIAADJIgbAAIAAj5IAaAAICcDKIAAjKIAbAAIAAD5g");
	this.shape_8.setTransform(73.3,24.2,0.392,0.392,0,0,0,0.3,0.3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgICBQgrgDgcgaQgcgZgJgqQgIglALgnQALgnAggXQAfgXAnAAQAuAAAiAeQAhAdAGAuQAGAmgNAkQgOAoggAVQgeARgjAAIgJAAgAgEhmQghABgWAWQgWAUgHAiQgGAeAIAeQAJAfAXATQAYATAeAAQAjAAAZgXQAYgXAGgjQAFgegJgeQgLgggYgRQgXgRgcAAIgEABg");
	this.shape_9.setTransform(59.6,24.1,0.392,0.392,0,0,0,0.4,0.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgMB8IAAj3IAaAAIAAD3g");
	this.shape_10.setTransform(49.4,24.1,0.392,0.392,0,0,0,0.4,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMB9IAAjfIheAAIAAgaIDUAAIAAAaIhcAAIAADfg");
	this.shape_11.setTransform(40.1,24.2,0.392,0.392,0,0,0,0.2,0.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgMB8IAAj3IAZAAIAAD3g");
	this.shape_12.setTransform(30.9,24.1,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhuB8IAAj3IBfAAQAvAAAkAaQAeAZAJApQAJAlgNAmQgMAngjAVQggAUgnAAgAhSBjIBDAAQApAAAbgcQAcgcAAgrQAAgpgcgcQgbgdgpAAIhDAAg");
	this.shape_13.setTransform(21.1,24.1,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhSB9IAAj5ICiAAIAAAaIiGAAIAABTIB1AAIAAAXIh1AAIAABbICJAAIAAAag");
	this.shape_14.setTransform(8.2,24.2,0.392,0.392,0,0,0,0.1,0.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhuB8IAAj3IBfAAQAuAAAlAaQAeAZAJApQAJAlgNAmQgMAngiAVQggAUgoAAgAhSBjIBDAAQApAAAcgcQAbgcAAgrQAAgpgbgcQgcgdgpAAIhDAAg");
	this.shape_15.setTransform(-11.1,24.1,0.392,0.392,0,0,0,0.1,0.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhSB9IAAj5IChAAIAAAaIiFAAIAABTIB1AAIAAAXIh1AAIAABbICJAAIAAAag");
	this.shape_16.setTransform(-23.9,24.2,0.392,0.392,0,0,0,0.4,0.3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgNB9IAAjfIhcAAIAAgaIDTAAIAAAaIhcAAIAADfg");
	this.shape_17.setTransform(-35.9,24.2,0.392,0.392,0,0,0,0.3,0.3);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgNB8IAAj3IAaAAIAAD3g");
	this.shape_18.setTransform(-45.2,24.1,0.392,0.392,0,0,0,0.1,0.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABjB9IgPjEIgBAAIhTCaIAAAAIhTiaIAAAAIgRDEIgbAAIAVj5IAaAAIBQCaIBQiaIAbAAIAVD5g");
	this.shape_19.setTransform(-55.9,24.2,0.392,0.392,0,0,0,0.3,0.3);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNB8IAAj3IAaAAIAAD3g");
	this.shape_20.setTransform(-66.6,24.1,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhSB9IAAj5IAcAAIAADfICJAAIAAAag");
	this.shape_21.setTransform(-75,24.2,0.392,0.392,0,0,0,0.2,0.3);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAAgCQADACgDADg");
	this.shape_22.setTransform(15.4,-10.7,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag4A2QgIAAgEgEQgDgDAAgIIAAhHQACgRAUAGIAFAAIADgCQACgBARAAIATgCQAEgDADABIABADIACABQAAgEAHAAIAKAAIARgDQANgBACAEQACgBAFABQAEABABADIgBAGQgBAEAFAAQAAgFABgBQABAIgBAOQgCAQABAEQAAAGgCAiIgDgEQgBgBgBgBQAAAAgBgBQAAAAgBAAQAAABAAAAQgBACAEAFQAAADgFACQgHADgLAAIgTgCQgLAAgbAEQgUADgOAAIgHAAg");
	this.shape_23.setTransform(48.4,-19.5,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhKA2QgLgHAKABIgCgFIgCgGIAAgIIABgIIACghQABgQAEgHQAFgIAUgCQAZgEAvgEIAGgBIAFADIAIgDIAFAAQABAAAAAAQABABAAAAQAAAAABABQAAABAAAAQAGAAgCgGIAMACQADABAFAKQADAHgBAJIgCAPQgBAPADAVQADAKgCAEQgBACgFACQgDABgDAAIAAAAIAAAAIgBAAIADACQgGgBgJACIgVAAQgIAAgjAFQgeAGgRABIgFABQgHAAgGgEg");
	this.shape_24.setTransform(-29.3,-19,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhABDIgIgWIgGgTQgHgaAHgOQADgGAHgCIANgBQAQAAALgFQAcgNAIgSQAGgOAMgCQANgCAIAGQAIAFAEAOIAGAXQACALAIAKQALAKgGAHQgWAcgUAOQgeATgbADQgQAEgIAAIgDAAQgNAAgFgKg");
	this.shape_25.setTransform(-63.5,-12.1,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhMA4IADAAQgQgBgBgTIACggIACgZQADgTAGgDQAFgEAUABIALgCQAIgBAFABQgFADABABIAIgFQAEgCAKAAIA7gDIAIgBQAEAAABAEIAGgEQAEgCAEACQAFAEAHAIQgHgCAAAGQAGAAABALIgBAQQAAAYgDANQABAAAAAAQABAAAAAAQABAAAAAAQABgBAAAAIADAIQABAGgCACQgDAEgKAAIgzACQhCAJgiACIgCgBg");
	this.shape_26.setTransform(-28.7,-26.2,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAzBMQgHgCgIgHIgOgMQgagVgQgDIgXgDIgPgCIgHAAIgBAAQgLgEgFgDQgJgGAEgOIAFgbQACgQADgKQAEgNAFgFQAGgHAMACIAYAGIAaAFQAKADAOAHIAYANQAaAMAMASQAHAJgGAOQgIAUAAAGIgDAaQAAAOgCAAQAAAAgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBgBgBQAAAAAAAAQAAgBAAAAQgBAAAAAAQAAAIgIAAQgEAAgIgDg");
	this.shape_27.setTransform(-63.2,-24.9,0.392,0.392,0,0,0,0.3,0.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhdAtQgCgFABgIIACgNIABgTQAAgLACgHQABgMADgGQAEgGAIgCQAKgCAkgDIAhgEIANAAIAEACIACADQABgEADgBIAJgBIAVAAIASgCQALAAAEAGQADADAAAFIgBAJIgBAVIgDASIgCAJQgCAFABAEIACgEQADADABAGQABAGgCADQgGgDgGAAIAHAHQgEACgCgBQAAgBgBAAQAAgBgBAAQAAgBgBAAQAAAAgBAAIgEABIgGACIgPABIgPABIhCAHIAAAAIACgBIgGABIAEAAQgVADgNABIgFABQgWAAgDgMg");
	this.shape_28.setTransform(-12.8,-11.7,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhHA4IgKgBQgHgBgCgDQgEgDAAgGIABgLIACgnIADgTQACgLAHgEQADgCAGAAIAIAAIAYgDIAUgDIASgBIAYgBIAYgCIAVgCQAMAAAHAGQAEACAAAFIAAAJIgBAvQgBAIAFAOIgGgDQgCgCgDAGQAHAAAEACQgHAGgSABIgbAAQgZAAgfADIgdAGQgOADgKAAIgFgBgAA0gyIAEAAQAAgBAAAAQAAAAAAgBQAAAAgBAAQAAAAgBgBIgEAAQAAABAAAAQAAABAAAAQABABAAAAQAAAAABAAg");
	this.shape_29.setTransform(-12.7,-26.3,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgSBgQgmgDgSgDQgPgCgGgKQgCgFACgHIAEgLQAGgPAIgKIAHgKQAFgHAFABQABgIAIgHIAMgQIAKgTIAKgKIABgCIgBgFIAAgDIAPgZQAEgIADgDQAIgFAPAEIAJAEQADABAJAAQAKAAAWAFQAPACACAJQADAKgIAOIgOAUQgMASgFAKIgOATIgIANIgIAIQgJAJgJAOIgGAMIgGANQAAAGgGACIgFAAIgHAAg");
	this.shape_30.setTransform(0.9,-18.8,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhYA6QgLgBgEgFQgDgEAAgTIABgcQAAgRABgGQADgPAIgFQAEgCAHgBIAMAAIAbgDQAogEASAAIAbgCIALACIAKAAQAFgBAJgEIAQAAQAPAEgDAjQgBAJAAAQIgBAIQgBAEABADIADAHQACAEgCADQgFAGgRAAQABgBABgBQABgBAAAAQAAgBgBAAQAAABgBAAIgIAEQgDACgFAAIgGgBQgQACgeAAIgsAGIgvAEIgBABIgIABIgFAAg");
	this.shape_31.setTransform(-12.6,-18.9,0.392,0.392,0,0,0,0.2,0);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAhCGIgaAAQgOgBgKgEIgCAGIgDgFIgFgBIgEgCQgBAAAAgBQAAAAgBgBQAAAAAAgBQAAgBAAAAIAGAAIgGgLQgBAAAAABQgBAAAAABQAAAAAAABQAAAAAAABIADAGQgFgCgBgEQgCgEAEgDQgJgCADgOIACgKIABgKQgCgFABgCQABgBABAAQAAgBABAAQAAgBABAAQAAAAAAAAIgEgDIgDgHIgBgOIgCgNIgCgNQgGglgBgRQgDgpADgOIADgNIADgNIAAgIQABgEAFgBQADgBAPAHQAFABAPAIQAFADAPAFQAOADAGAGQAAAAAAgBQgBAAAAgBQAAAAAAAAQAAgBAAAAQAGAFABAIIgBAOQgBAVABAVQAAAGAFAfIAGAoQAEALgDAJIAAAGIADAGQADAGgBAKIgBARIABAMQABAHgBAFQgDAHgIAAQgGAAgHgCgAAHABQAAABAAABQAAAAAAAAQAAABABAAQAAAAABAAQADgCgDgCg");
	this.shape_32.setTransform(22.5,-14.9,0.392,0.392,0,0,0,0.3,0.2);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("ACqA1IgNgDIgPgBQgMgEgFAAIgIABIgLgCIgKgCIACABIgtgDIgZABQgPABgJgCQAAADgJAAIgmADIg2AFIgbACIgbABIgXAAQgNgBgLgEQgQgIAPgcQAUgcADgHQAEgNAGgEQAEgEAFAAIAJABIAVgBQAMAAAEAIQABgBAAAAQAAAAAAAAQABgBAAAAQAAABABAAIADACQAAgFgDgEQAIABAIgBIAJgBIAIAAIAigCQAYAAALgDQAFgCAYgCQA7gDAQACQAyAEAcAAIgCAGIAOgDQAGAAAGAEQAJAGgDAWIgCAJIgCAHQAAAPgCAIIgCALIACAGIAAAEIgFAAIgBAJQgHACgFAAgAAsAhQgBAAgBAAQAAABgBAAQAAAAgBABQAAAAAAAAIAIgBQAAAAAAAAQAAgBgBAAQAAAAAAAAQgBgBAAAAIgCABgABNAWIABACIABgCIAAgDIgCADgAiJATQACAAABAAQABAAAAgBQABAAAAAAQAAgBgBAAIgFAAIAAACIABAAIAAAAgAhVAEIAHADQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBIgCgBQgBAAAAABQAAAAAAAAQAAAAgBAAQAAABAAAAgAAUgdIACgFIgDgDQgBAEACAEgAh9gfIAAAAIAAAAIAAAAIABgBIAEgEIgGAAgABzgwIAFgBQAAgCgHAAQAAABAAABQABAAAAAAQAAABAAAAQAAAAABAAg");
	this.shape_33.setTransform(1.8,-11.7,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AARA2QgQgCgeAAQgOAAgggCQgegCgRAAIgTgBQgHgBgPACIgWABQgPgDgGAAIgDAAQgHAAAAgKIABgTQACgcACgFIAEgOQACgNACgCQAFgHAOAAIAXAAQAzgCAKAAIAeABQAKACARAAIAeADIAQACIBAAAIAQgBIARAAQANACAOgCIAegCIANgCIANgCQALAAAFACQADABACADIAEADQAAAAAAAAQABABAAAAQAAABgBAAQAAABAAAAQAGAAADAGQAAABAAABQAAABAAAAQAAAAAAABQgBAAAAgBIgEgDQADAJgCAEIgDAGIgCgBQgDACAAAFIAAAHQAAACgDABIgEAHIAAAIQABAEgBACQAAADgDAGIgDAIIgCAHQgBADgEABQgCABgFgBQgFgCgDAAIgHAEQgEABgCgGQgDAEgDAAIgIAAIgFAAIgDgGQgEAHgKABIgRAAIgtABIgfACIgLgBgADBAEIACgBIAAAAQAAgDgFgCQAAADADADgAgpgHQgFAEAFAAQACABABgFIgBAAIgBAAIgBAAgADQgaQABAIADgGIgBgBQAAAAABAAIgEgBIAAAAgAB9ggQgBAAAAABQAAAAAAABQgBAAAAABQAAABAAABIAHgDIgFgCIAAAAg");
	this.shape_34.setTransform(2.2,-25.8,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgbDwQgDgBgBgEIABgFQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAIgEgBIgEgDIgDgCQgBgBAAAAQgBAAAAAAQAAAAgBAAQAAAAgBABQgBgFgEAEQgBgOgCgCIAAgBIAAAAIAAgBQAAgCACgDIAGgHIgIgDIAFAAIgBgHQAAgCgDgDIAFAAQAAgBAAAAQAAgBABgBQAAAAAAgBQAAAAAAAAIAFgFIgHABQgDAAAAgGQADgEAAgCQABAAgCgFIABgBIgBgFIgBgIIABgRIACglIAAgbIABgEIADgBQgDgBAAgEIAAgHIAAgTQABgSAEgaQACgRAAgkIgCiJQgDgLABgGQAAgHAMgBIASACQAOABAbAJIgDAEQAIgBABAEIAAALQAAAAABAAQAAAAABgBQAAAAAAAAQABAAAAgBIADgDQANAhACA3IABAvIgBAvQAAAPgDAcQgDAfAAAQIgBAxQAAAUgBADIgEAGQAAAAAAABQAAAAAAAAQAAAAABAAQABAAABAAIAAAZIgDgCQAAgBgBAAQAAAAAAAAQgBAAAAABQAAAAAAABQgBADAEAFIgCAHIgBAHQAAABAFAAQgDADAAACIAAAHIgDgEIgCgEIgCgDIAAADIgBAFIgEAEIAHAHIADgEQACADgFAGQgGAGADACIACgDQAEACAAADIAAAIQgBgBAAAAQgBAAAAgBQgBAAAAAAQAAgBAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAgBABAAIgKACQABAAAAABQAAABABAAQAAABgBAAQAAAAgBAAQAAAAgBABQgBAAAAAAQgBAAAAAAQAAABAAAAQAAAAAAAAQAAAAABAAQAAAAABAAQABAAAAAAQAEgCACACQgBAAAAABQgBAAAAABQAAAAAAAAQAAABAAAAIADAFQgDACgDgBIgGgEIgBAHQgGgBgDgDIgDgEQAAgBgBAAQAAAAgBAAQAAAAgBAAQAAAAgBABQABAAAAABQAAAAABABQAAAAAAAAQAAABgBAAIgDAEIgBgGIgCADQgBgDgDADQgDACAGACQAAAAAAABQAAAAAAAAQAAAAgBAAQAAAAgBAAIgEgBIgEAAIgMgCIACAFIgHgBgAgbCmQABAAABAAQAAAAABAAQAAAAABAAQAAAAABAAQgCgCgGAAQAAAAABAAQAAABAAAAQABAAAAABQABAAAAAAgAAcCiQAHAAgDgFQgDAGgGgEQgCAEAHgBgAguCTIABgEIgCgEIABAIgAAlBjQABgBAAAAQABAAAAgBQAAAAAAAAQgBgBAAAAIgEgCIgFAAQAGAGACgBgAABA2QABAAAAABQABAAABgBQAAAAABAAQAAgBABAAIgGgDIAAABIAAAAQAAAAAAABQAAAAAAABQAAAAAAABQABAAAAAAgAAkiIIACgDIgEgEQACADAAAEgAAhjKIAAACQAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQADgBgCgEIgBgCIgDADg");
	this.shape_35.setTransform(55.1,-19.4,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAWDdQgDgEAAAIQgSgCgHACQgQACgGgEIAEgCIgIgDIADgCIgEgCIgDgBIACAIQgHgCgCgKQgCgKAEgFIADACQAAgFgEgCIgGgCQgFgGAJgEIgDgBQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIgBgVIAGACIAAgKQgGADAAgDIAAgJQAAgFgCgCIgCgIQgCgSAFgFQgGgDAEgZIACg5IABgaQAAgFACgIIACgCIgCgEQgBgFACgNIACgWIABg2QgCghABgRIABgMIgBgLIgCgIQgBgEACgDQAEgFAOAAIASgBIAUgBQANAAAJgCQAJgDAEABQAGACACAIQABAEAAAXIABA0QACA3gGAxIgDALIADAFIABAIIgDAmIgDAuQgBAGABAMQABAMgBAGIgBAIIABAEIgBAKIABAZIABAdIAAAQQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAQAFAFgBAJIgEgDIgFACIABgHQgFAAgDADQgBAAAAABQAAAAAAABQAAAAAAABQAAABABABQAAADgBACIgDABQgDAAgCgFgAArC5QAAABAAAAQAAABABAAQAAABAAAAQAAAAABAAIABgFIAAAAIgBAAQAAAAgBAAQAAAAAAABQAAAAAAAAQgBABAAAAgAgmC0QAAAAAAABQAAABAAAAQABAAAAABQABAAABAAIACgFIgFgCIAAAAIAAAAIAAgBIAAAFgAAnClQAAAAAAAAQAAABAAAAQAAAAAAABQAAAAABAAQAAABAAAAQABAAAAAAQAAABABAAQAAAAAAAAIABgDIgCgFIgCAEgAguCKQAAABAAAAQAAAAABABQAAAAABAAQAAAAABAAIgCgFQgBAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAgAAoCHIgBABQgBABAAAAQAAABAAAAQAAAAABABQAAAAABAAQADACgBgEIgCgEQgBABAAAAQAAAAAAABQAAAAAAAAQAAAAABAAgAgrBeIADgFIgCgBQgCAEABACgAgjBVIADADQAFgCAAgBIgEgBIgEABgAATA4QgBAAAAAAQgBABAAAAQAAAAAAABQAAAAAAAAIADAAQABAAAAAAQABAAAAgBQAAAAAAAAQABgBAAAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQAAgBgBAAgAggAsQgDADAEAAQAEABACgDIgFgBIgCAAgAglguIgBAGQAGgBAAgDQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAgBgBAAIgBAAIgCABg");
	this.shape_36.setTransform(14,-19.4,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgeDuQgEgGgCgFIgHgIIABACQgHgKgBgLQgBgIAAgQIAFgzIABhAIABgDIgCgCIABgcQAFh8gGhWIAAgZQgBgPgCgJQgCgLADgDQAEgEAOAAIAvgBIATABQAKABACAKQACAKAAAQIgCAaQAAASAEAhQABAXgCBOQgDBWgBARQgCASAAAiQAAAjgCASIgKgBQAAACAFACQAEACAAADQACANgCANIgCALQgCAFgFACQgLACgFADIgKAEQgHACAAADIgBAHQgCAEgDAAQgLAAgNgNg");
	this.shape_37.setTransform(-36,-18.2,0.392,0.392,0,0,0,0.3,0.2);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgMEBQgFgDgGAHQgDgFgGgDIgLgIQAEgBACgFIgCABIgCABIgCgCQgDAGgDgKQAAAAAAgBQAAAAAAAAQAAgBAAgBQAAAAAAgBIABgEQgEgGABgFQgBAAAAAAQgBAAgBgBQAAAAAAAAQgBgBAAAAIAAgGIAAgOIABgbIAAgUQAAgNAGgGQgFgEAAgNQgCgQACgHQACAFAAgHIACABIgCgEIgDgDQgBgCAAgJIgCheQgCgZAAgxIgBgjIAAgMQAAgJAFACQgEgCgBgCQgBgBAAgIIAAgZQgCgOABgHQACgEAAgDIAAgGIgCgFIgBgWQgCgLACAEQAFgDAKABIAEgCIAFgBIAlABQAKAAAIACIAZAFQAOAFACALIABANIgBANIABAkIADC4IgBANIACASIACAiIgBALIABAIIAAAJIgBAFIgBAFIACAEIABAGIAAAhIgCAhQAAAUgGACIAEAFQACADAAADQAAACgEACQgDACgBADQAAAAAAABQAAAAAAABQAAAAABAAQAAAAABgBQAAAAABgBQABAAAAAAQABAAAAAAQABAAAAABQADADgEADIgHAEIAFACQAAAAgBABQAAAAAAAAQgBABgBAAQAAAAgBAAIgFABQgGAFgFABIgRACIAAABQABACgHAAQgGAAgJAKIgBgDIgEAEQgDgGgEgCgAAYDxIgFADQgIABgDAEIAHABIABAAQAAgDAGgCQAGgCADABQABgBAAAAQAAgBAAAAQAAAAAAgBQAAAAgBAAIgEACIgDgCIAAAAgAAwDsQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAgBIAAAAgAg3jGIAAABQAAAAABAAQABgBAAAAQAAAAAAAAQAAgBgBAAIgBABg");
	this.shape_38.setTransform(43,-18.3,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgHEGIgOgKIAEgFQACgDgDgDQgDAGgBAAQgBAAgDgFIgDgEIgFgEQgEgDgCgMIgDgMQgBgGABgKIAAgRIABABIgCgGIgCgEQgBgEADgGIADgDIgCgEIgDgKQgDgNABgSIABgPQABgKAFgEQgHgCAAgIIAAgNIAAgtQAEABgCgFIgCgGQAAgKgCgGIgBABIAAgyIACgIIADgIIgCABIgCACQgCgSAGgKQgEACAAgJIAAgNIAAggQAAgqACgUIAAgXQABgPAJgFQAFgCAFAAIAJABIAMAAIAMACIAWABQAOACAEAIQADAHAAANIgCAUIgBBfIABAJIgBAHIAAACQgEAAgBACIAEAFQABACAAAEIABAtIgCASQABARAABSQgBAAgBgBQgBAAAAAAQAAgBAAABQAAAAAAAAIADAGQACAEgBAHIgBAKIABAZIABANQAAAHgCAEQABAAABABQAAAAABAAQAAABAAAAQAAABAAABIgBAHIACASQADAYgCAHIgCAFIABADQADALgBAEIgEAIQgDAFgDABQgCABgFgBQgEgCgCABIADAEIgMgBQgHAAgFADIgDADIgEABIgCgCQgBgBAAAAQgBAAAAAAQgBAAAAABQgBAAgBAAQACAAAFAEQAFADgBABQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAgHgEg");
	this.shape_39.setTransform(-20.3,-17.5,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAAAAIABAAIAAABg");
	this.shape_40.setTransform(72.3,-14.4,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgJBsIgSgGIgIgEQgFgDgDgBIgLgCQgCABgCAEIgDAFQgEgGgDgBQgCAAgFABIgHACIgHAAIgEgEIgGAAQgDAAgBgDQABgHgDgBIgIACIgFgCIgJgIIgDgDIgDACQgDAAgCgCIgFgEQgCgBgDAAIgBAAIgCgCIAAgCIgDAAIgEgBQgCAAgFgFQgagVgKgOQgUgggJgaIgJgZIgDgKQgBgEAGgEQAGgFAUgJQASgIAJgCIAXgHQAOgBACAOIABAIIAGAGQAEAGAFANIAQAcIAIAJQAFAFgCAFQAEgBABACIAEAEQACACAGACQALAFAMAKQACgFANAJIAQALQAQAGAKgBIAFgBQAAAAAAAAQABAAAAgBQABAAAAAAQAAgBAAAAIgCAAIAAgBIAGgBQADAAABAEQACgHALgDIAQgIQAAAEABABIAFABQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBIADgCQAEgEACAAQABAAABAAQAAAAABAAQAAAAABAAQAAABAAAAIACAEQACgJAFgBIALgEQAHgCADgDQACAGABgCIADgGQADgGAIgGIACADIACACIABgCIgBgCIABgFIAEgFIATgWQAGgGAEgTQAEgSAGgIQAGgHARAFIAYAJIALACIAIABQAEAAAGADQAGADACADQAGgEABAIIABAIQgBADgEAEIgDANIgGAQIgDAKQgCAGgCADIgJANQgHAPgDADQgSAWgQAHQACgHgDADQAAABgBAAQAAAAAAABQAAAAAAABQgBAAAAABIAAADQgBADgGAEQgOAEgEAEQgLAIgVAIIgnASQgcAIgOAGQgLAFgMAAQgGAAgIgDgAAfAgQAEgEAAgBIgDgFIgBAKgAByAWIgCADIABADIAAAAIAGgGIgDgCIgCACgAAsAWIgBADIAAAAQABAAAAAAQAAAAAAABQAAAAAAABQAAAAAAAAIAEgHIgBAAQAAAAgBAAQAAAAgBAAQAAABAAAAQgBABAAAAgACaAbQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIgEgDQgCACADADgAgzAWQAAABAAAAQAAAAABABQAAAAAAAAQAAABABAAQABAAAAAAQABAAAAgBQAAAAAAAAQAAgBAAgBIgCAAIgCAAgAhTgDIACADIACAAQgBgDgDAAIAAAAgADbgaIACAFIACgCQABgBAAAAQAAgBAAAAQAAgBAAgBQgBAAgBgBIgCAAQAAAAAAAAQgBAAAAABQAAAAAAAAQAAABAAAAgAiCgsQACAHADgBQAEgCgEgFIgGgIIABAJgACOg9IAFAFQABgBAAgBQAAAAAAgBQAAgBAAAAQAAAAgBgBIgCAAIgDAAg");
	this.shape_41.setTransform(68.8,-14,0.392,0.392,0,0,0,0.2,0);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("ACgB4QgDgEgDgHIgFgMQgIgNgEgMQgBgFgLgOIgHgKIgJgJIgTgPQgMgJgKgBIgJgDIgHgDIgKgBIgJgDQgWgMgbgGQgRgEgJAAQgPgBgLAFQgPAGgZAXQgTATgHAWIgHAaIgFAaQgDAIgDADQgEADgJAAIgYgFQgQgDgMgEQgQgEgEgDQgKgHACgLIAHgUIAFgZQADgPAFgKQAKgXASgTIAcgbQALgJAfgPIALgFIAKgEQAIgGABAHQABAAAEgIQADgDAMgCIAMgDQADgCADgFQADgFADgBQAEgCAGABIAKABQAIgBAQACIAKgCIAMgCQAHABAMAJIAzAZQALAEAKAGIAXANQAcALAOANIAHAIIAGACQAKAJgGADIAJACQAEACgDAGQAIgBAIANIAKAVIAEAMIgBADIADACQAIAJAEAOIAEAKIACALQgBAMgNAHQgGAEgEABIgGABIgFgBQgKAAgFAFQgKAIgHACIgGAAQgJAAgEgEgACiB3IABABQAAABABAAQAAAAABAAQAAAAABgBQABAAAAgBIgFgDgACyAsIAHABQAAAAAAgBQAAAAAAAAQgBAAAAgBQgBAAAAAAIgFABgABNAFQACgFgGAAQACACACADgAjDACQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIACgFQgBAAAAAAQgBAAgBAAQAAABAAAAQgBABAAAAgAh2hTIADABIAEgBIgEgBIgBAAIgCABg");
	this.shape_42.setTransform(68.9,-23.7,0.392,0.392,0,0,0,0.2,0.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("ABGD3IgRgGQgWgHgNgHQgggRgbgfQgKgLgMgVIgTgiIgXgjQgIgPgHgTQgLgjAEgqQAFgiADgJIAIgSIAIgSQAIgTANgPQAOgSAIgFQAIgFAPgPQAJgHARgSQAMgKATgGIAkgKQAOgDAagDQAHgBAHADIANAIQABABgBAAIgDACQALAGgDARQgBAJgHASIgDANQgBAEgDACIgFAEIgGAIQgDADgFABQgMAAgGACQgSAFgRARIgNALIgMANQgDAEgIAGIgDACIgBAFQgBACgDAFQgDAEgBAEIgBAHIgBAHQgCAGgIAHIgEAQQgCAMAEAXQABAFAFAKQAFAKABAGIAEASQACAKADAIIAGANQADAIAEAFQAJAOALAHIAQAKQAMADAEADQAGADAKACIASACQAJAFABAFIAAAEIgCAEIgCALQgCADAAAHQAEAGgBAEQgBAEgEAFIgDAMQgFAUgHAGQgFAEgHAAIgEAAg");
	this.shape_43.setTransform(-73.2,-18.5,0.392,0.392,0,0,0,0.3,0.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AC0DhQgFgCgEgDIgHgHIgPgPQgJgGgHgNIgCAFIgugkIgngZIgugcIgLgHQgJgFADgEQgJABgLgLIgWgRQgNgJgNgLIgKgIQgFgGACgFQgFACgFgEIgCgEIgCgEIgKgDIg8hDIgXgbQgKgNAAgFQAAgIACgMIAEgTIAGgjIAEgOQAEgIAGgCQAJgDAOAOIAWAWIAWAXQADAEAIAFIAGAJIAUAXQAKALAQAOIAbAYIA1AoIAYAPIALAFQAFADgCAEQAGgDAHACIALAIIAKAGQAGAEAFABQACgJABgMIAAgTQACgNAAgcQACg5gCgcIgFgoIgGgZQgBgPARAAQAKAAARAEQAfACAOAMQAJAHAAAMQAAAFADAEIAEAKQADAPAAAOIACAQQABAJgBAHQgBAIACATIgDAZIACADQACAJgBAPIgCAZIgDA2QAAALgCAHQgEgEACAEIACAIQABAFgCALQAAAIAEAHQAFAGgCAEQAGABABAGIAAAQQACAMgFAVQgBADADAGQAEAJgCAJIgDAKIAAAHQgBADgFAAQACAGgOAAIgOgBgACNC3IAAACQABABAAAAQAAAAAAAAQABAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAgBgBIgBACgAhKAjIACADIADgEIgCAAIgDABgAiFgSQACACAFgDIABgBIgFAAQAAAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAg");
	this.shape_44.setTransform(28.7,-19.7,0.392,0.392,0,0,0,0.2,0.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("ACYD+IgFAAIgFgBIAEgCQAAgBAAAAQAAgBAAAAQgBAAAAAAQAAAAgBAAIgDABIgCgEIgCgGQgFADgGgXQgJgSgDgKQgCACgFgMIgHgOQgEgHgQAAIgOABIgPACIg5AEQgIAAgEgCQgCgDgCAAIgFAAQgDgBgEgEQgDgEgBgEQAAgEADgHIAEgLIAIgcQAMghARgBIAjAAIAIgBQAFAAACgCQADgCgBgDIgDgGIgVgwQgNgjgLgPQgRAZgTAhIggBAQgOAggRAeIgcA7IgRAgIgFALQgDAGgFACQgDABgTAAIgbgBQgygEAEgUQABgFAGgIIAIgNQAJgPAFgOQAPgkAOgcIAJgSQAEgJgBgKIAHgMIAEgGQACgCAEAAQgFgFAHgMQAIgLAEgKIAFgIQAAAAABgBQAAAAAAAAQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAQABAAAAgBQAAAAAAAAQAEgBgEgEIAEgKQACgGAEgGIACgFQABAAABgBQAAAAABAAQAAAAAAAAQAAAAAAAAQADgEAAgQQAAgOAFgEIAKgFQADgDAFgHQANgPANgWIAMgTQAIgMgCgIQAAgFgJgKQgHgIABgGQACgHAHgIIAMgNIAbgcQAHgHAFAAQAEgBAGAHQAJAJAMASIAOAUIAIARQANATAHAVIAHAUIAKATIADAKQABAGACAEIALAWIATAvIAJAQIAGATIABAEIAEAFIAFANQAHAQADAEQAHAGACAHQADAHABAPQAEANAAAJQADgDAEAHIAEAKIAHAPIAIAPIAEAHQABACAEABIAGABQADABACADQAEAFACAOIAFAKIAEAKQAAgBAAAAQAAAAAAAAQAAAAABABQAAABAAABIAAAAIABAEIgBgDIADAPQACAKgGAGQgFAFgLgEIgQgGQgPgGgUALQgKAEgEAAg");
	this.shape_45.setTransform(-49.5,-18.9,0.392,0.392,0,0,0,0.2,0.1);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-78.4,-29,156.9,58.2);


(lib.Анимация17 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Capsule();
	this.instance.setTransform(-51,-65,0.9,0.9);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-51,-65,101.7,100.8);


(lib.Анимация16 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F43").s().p("AhlSoQgggegegnQg3hGgkheIgQgtIgPgvIgCgEIgDADQgeAwgtAyQggAjg3A1QgiAfgrAdQgjAZgxAaQgHADgCgCQgCgBgBgHQgKiFAnhyQAJgdASgpIAdhEIABgGIgFACQhXBBh6APIgTABIgSABQgFAAgBgDQgCgBACgFIAeg3QAQggAdgjQANgQApgtQAEgGANgLIACgEIgFAAQgRAAgpAPQgsAQgNABQg/AGgXgBQglgEgkgXIgJgFQAPg2AxgzQAngpBFgwQgRgagNgYQhKAYhKAKQARg3Ang4IABgDIACgEIgIACIhKAbQgtAPgXAEQgLACgRAAIgdgBQgXAAAJgUQAGgJANgRIAIgOIAQgVIAbgiIAdggQAJgJAQgNIAagWIAEgFIgIgBQgnAGgQABQgfADgYgEQg9gLgtgaQgKgGAAgEQAAgCAJgHIA6gjQAigVAZgNQAOgHAWgGQAagGAMgEIAGgBIgHgDIgrgIIgsgIQg3gMg1gsQgBgBAAgEQAAgBABgBQAAgBAAAAQAAgBABAAQAAAAABAAIAlgRQAXgKAQgFIAzgNIA0gKQAFgBALgBIARgCIADAAIADgBIgEgEIglgZIgkgbQgIgGgIgLIgPgSIgLgOIgKgPQgJgRADgFQADgFATgCQAggCBEgCIAJACIAJADIALABIALAAIA1AIIAKABIgGgIIgugzIgug0QgKgLgNgTIgXgdIgCgFQAFgEACAAIA0gJIAEgBIACgCIgEgEIgpgjQAZgKBdAHICoASIATgWIg5gvIgYgWIg9hHIAFABIAJABIgGgHQgWgYgTggQgRgbgQgjIgSgrIgSgsQgDgHACgCQACgCAIAAQAjACAVADQAgAEAWAKIAvATIAvATIAJAEIAHADIgEgHIgjg7QgSghgJgdQgPgqgQhHQgEgOAEgDQADgDAQAFQAgAMAoAWQBAAiA9A+QALAMARATIAdAhIACgDQAHgvASg2QAMgkAag+QAQgjAYgmQATgeAeglQAEgFACABQACAAADAGQA0BkAIBlQADAaAAAlIABBAIAAAFIAEgEQAthPBbg0QAJgGASgIQAIgEAAAIIgFA1QgCAegKAmQgFAQgQAwIgIATIgBAEIAEgBIAjgPQAVgJAQgFIgMgkIADAEIADADIAEADIgCgIQgRg+gEhLIgDhbQgBgIADgBQACAAAHAGQAcAVAXATQAYAXAVAXQAZAlAoA6IAMASIgCgJQgJhVAAg0QADglAGhKQACgOAEgBQAEAAAMAPQAdAlAbApQAzBYAXBSQAIAeAMA8IABAFIADgCQAegdAkgYQAfgUAsgWQAggNAjgHQAfgGAngCQAFAAACADQABACABAGQAAA8gIAuQgLA4gXAtQgTAigoA6IgDAFIAEAAQAqgHAuALQAkAJAvAXIANAKIAPAJQAIAFgGAFIgeAhQgXARgXAOQgUAMgeANIgIADIgIACIAIAKQAnAbAUAUQA+A8AuBbIAEAKIgmA1IAFAPIAYgHIAlgJIBvgNIgFAEIgGAHIAJAAQAngGAsABQAkACAuAIQAXADAgAHIA3ALQAJACABAEQABACgHAIQgZAjgQARQgZAcgYARIgyAiIgyAfIgSALIAKAAQAzACAeADQAsAEAiAKQAvAMBWAeQAQAGABAFQAAAFgPAKQgiAZgtAYQhMAohlAUIgwAHIgvAGIgGABIADAEQAqAlApA2QAbAkAsBBQAZAnAVAwQARAnARA1QACAHgCACQgCACgHgBQiFgOhpg6QgagPgmgYIg/goIgEgEIACAGQAuBigHB6IgCASQgCANAAAFQgCAJgHgFIgxgnQgcgWgegiIgzg/IgMgVIgEgDIgCAFIgIAtQgEAbgHARQggBhg7BAIgGAIIikhRIgKAmQgFAVAAAVIgYgIQgqgMgbgYQgCgDgGgCIACAIQANAmAHArQAFAkAAAuIgBBwQAAAKgDABQgDABgJgEQgmgTgVgNQgfgTgWgVQgcgcg2g6IgHgIIgHgHIABAKQAHA0ADAcQADAsgCAkQgEA0gPBVQgEARgEACIgBAAQgEAAgMgLg");
	this.shape.setTransform(-14.2,-24.8,1,1,0,0,0,-14.2,4.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-118.5,-149.3,237.1,240.8);


(lib.Анимация15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F43").s().p("EAIoArwQgHgBgLgLQhohohBhdQhPhxglh2QgZhdggirIgDgLIgHAHQg8BVhkA7QhLAuh5ApIgoAIIgpAIQgWAFAAgRIgChuQAHhFARhBQAOg2AdhLIAJgSIAKgSIgfgEQhyAVhEABQjVADjshPIgZgIQgPhMgMhSIghgTIgeA4QggA0gPAbQhZBthRBnIACgOQAAgDgCgUIgPAQQg4BOhPBJQhCA8hcBCQgvAihCArIhyBLQgUANgGgEQgHgEgDgYQgPhpgDg5QgFhaAMhJQAKg6ARhVIAdiQIANgyIgTASQhaBUg5AuQhUBFhMAsQhmA7jHBeQgoATgJgHQgKgIAIgrQAShmAkh3QA+jKCMjPQAbgnAsg4IBJheIAGgKQgGgCgFAAQiJAIikgWQhvgPi6gnQhugXh4gvQhigmh4g+QgQgIAAgIQAAgGANgLQEAjNEZhRQBGgUBrgXICzgmIAOgEIgMgGQj7hXjHjfQgLgMgRgXIgaglQgPgSAXgEICYgSQBWgLBvAJQAxAECTASIA6AMIAMAAIgGgKIhAhcQgmg4gUgpQhvjdgIjUIgDgYIGmiPIgwhSQgdgvgigjIA3gdQBcgzBZgDQAIgBAPgGQgQgLgDgBQhXgohWhBQhHg2hRhPQg0gyiKiRQgQgRACgHQADgHAXgIQBighA7gOQBXgVBKgCQBigCDDAFIAbACIAZABIgVgQQhlhMg1gsQhThHg5hDQhThih5irQgagkAFgKQAGgLAsgBQBrgBB4AOQDVAZDiBkQArATA/AhIBqA3IALAEIAAgMQgfiFgIilQgGhyAFi8QADhwAYh+QAUhoAniBQAFgRAIgBQAGgBANAKQD3DWCDEHQAhBCApBkIBFCpIAHANIAEgNQAnkFC5juQAKgNAUgUIAfghQAIgJAGACQAGABADAKIAuCTQAaBUAMBuQAFAzAICSQABATgCAnIACALIAJgHQAegcAthhQAwhpATgZQBgh2AugmQBFg4BngYIAXgIQBCB3AFCtQAECKglDLQBLAQBBASQBSioByiRQA/B9AfCiQAAAFADAFIAFAIIAKgRQA6h/AYgxQAyhmAhguQAQgYAdgdIA0gxQAognASAzQAIAYAEA0QACANAIAbQAIApACAYIAKBpQAGA+ABAqQAAAhgEAxIgIBRQgBADADAPIAOgMQA6hPAZgdQAxg6AygjQB8hYB6gfQAcgHAGAFQAFAFgGAbIgmCiQgXBegVBBQgMAkgcAxQghA3gPAcIgGAMIAOgGIBag+QA2gmAmgXQB1hHCpgRQADAAAGAJQAFAIgBADIglBfQgWA3gVAmQgbAwgnA9IhGBqQgJAOgQATIgbAgIgEAGIgEAGIAOAAIBsgUQA/gLAtgFQAYgCAhADIA5AGIAsAFQAZADARAGQAtAPAEANQAEAOgeAiQg1A+hwB4QgFAGgOAFQgPAGgGAEQgIAGgNANIgUASIhpBNIgUARIAYADICqAJQBqAGA+AEQAkADA3AIIBaANQAMADAAACQgCAOgEAEQgYAkgyBGQgCADgBAFIgDAIIAQAAICDgLQgYA9ivCTQjdCyhlBTIAEBHIC3gUIBOgEQCSAOBTAGIgLAGIgPANIATADQBSADBYAVQBKAQBYAiQAtARA+AaIBqAtQATAIAAAGQABAGgQAOQhAA6gpAfQg9Aug5AZQgrAThGAdIhyAvIgVAHIgUAIIAVAFQBqAaA2ARQBYAbBDAgQBiAwCXBdQAfAUgBAKQgCALglASQhLAjhpAfQiqA0jVgCQgoAAg9gEIhkgIIgKAAIAEAJQBEBdA+B+QApBUA9CWQAjBZAXBqQATBXAOBxQABAQgFADQgFACgNgEQkJhUi8igQgwgphChAIhuhsIgKgIIABAMQA5DYhAD2QgHAZgTAvQgGAUgNgPIhUhjQgxg4guhSQgUglg3hvIgTgvIgGgIIgEAJIgkBYQgVA1gTAhQAtAYAmARIgMgBIgLAAIgKABIAQALQCLBPCFB7ICjCXQAPAOgDAFQgDAEgXADQhWAMhHADQhRAEhMgFQhugPirgfIgxgLIARAOQCiCBBaBbQA8BEB0CMQAWAbgGAHQgHAHgtgFQhygOh2gZQjxg+i3hnQhBgkh8hUIgKgGIgCAIQgCBlgVBpQgSBYglBwQgiBPgwBIQgrBAg/BHQgIAIgHAAIgDAAg");
	this.shape.setTransform(3.7,-11.5,0.45,0.45,-72.2,0,0,-0.2,-0.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-131,-135.2,262.7,268.4);


(lib.Анимация14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#8DA34C").s().p("AvnXbMAAAgu2IfOAAMAAAAu2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-150,200,300);


(lib.Анимация13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#342F43").s().p("EAG6AjAQgGgBgJgJQhThTg0hKQg/hbgeheQgUhLgaiIIgCgJIgGAGQgwBDhPAwQg8AlhhAgIggAHIghAGQgSAEAAgOIgBhYQAFg3AOg0QAMgrAWg8IAIgOIAIgPIgZgDQhbARg3ABQiqACi9g/IgUgGQgMg9gKhCIgagPIgYAtIgmA/QhHBXhBBTIACgMIgCgSIgMANQgsA+hAA6Qg0AxhKA0QgmAbg0AjIhcA8QgPAKgFgDQgGgDgCgTQgMhUgDguQgEhIAKg6QAIgvANhEIAYhzIAKgoIgPAPQhIBCguAmQhDA2g9AkQhRAvigBLQgfAPgIgFQgHgGAGgjQAOhSAdhfQAxihBwimQAWgfAjgtIA7hLIAEgIIgIgCQhuAGiDgRQhZgMiVgfQhYgShfgmQhPgfhggxQgNgHAAgGQAAgFAKgIQDNikDhhBQA4gRBWgSICPgeIALgDIgKgFQjIhGigiyQgIgKgOgSIgVgeQgMgOATgEIB5gOQBFgIBZAGQAnAEB2AOIAuAKIAKAAIgFgIIgzhKQgfgsgQghQhYixgHipIgCgTIFRhzIgmhBQgXgmgcgcIAsgXQBKgpBHgCQAHgBAMgFIgQgKQhFgghFg0Qg4grhCg/Qgpgohvh0QgMgOACgGQACgFASgGQBPgbAvgLQBFgRA7gBQBPgCCcAEIAVACIAUABIgQgNQhRg9grgkQhCg4gug2QhChOhhiJQgUgdAEgIQAEgIAjgBQBWgBBgALQCrAUC0BQQAjAPAyAaIBVAtIAJADIAAgKQgZhqgHiEQgEhcAEiWQAChaAUhkQAQhTAehnQAFgOAGgBQAFgBAKAIQDGCsBoDSQAbA1AhBQIA3CHIAFAKIAEgKQAfjRCUi+QAIgLAQgQIAZgaQAGgIAFACQAFABACAIIAlB2QAVBDAJBYQAFAoAGB2QAAAPgBAfIABAJIAIgGQAYgXAkhNQAmhUAPgUQBNhfAkgeQA4gtBSgTQAEAAAOgGQA2BfADCLQADBugdCiQA8ANA0APQBCiHBbh0QAyBkAZCCIACAHIAEAHIAIgNQAvhmATgnQAohSAaglQANgTAYgXIApgnQAggfAOAoQAHAUADApQABALAHAVQAGAhACATIAIBUQAFAxAAAiQABAagEAoIgGBBQgBACACAMIAMgJQAuhAAUgXQAoguAngcQBkhHBhgYQAXgGAEAEQAFAEgGAWIgeCBQgSBLgRA0QgJAdgXAnQgbAsgMAXIgEAJIALgEIBIgyQArgfAegSQBeg5CHgNQADAAAEAHQAFAGgBADIgeBMQgSAsgQAeQgWAngfAwIg4BVQgHALgNAQIgWAZIgDAFIgDAFIALAAIBXgQQAygJAkgEQATgCAaACIAuAGIAkAEQATACAOAFQAkALADALQAEALgYAcQgrAxhZBgQgFAFgLAEQgMAFgEADIgRAPIgQAPIhUA9IgQAOIATACICIAHICGAIQAdACAsAHIBIALQAKACAAACQgCAKgDAEQgTAdgoA4IgDAGIgCAHIANAAIBpgJQgUAwiMB2IkBDRIADA5ICSgQIA/gDIC3AQIgJAEIgMALIAPACQBBADBHAQQA7ANBHAbQAkANAxAVIBVAkQAPAGAAAGQABAEgNALQgzAvghAYQgwAlguAUIhbAnIhbAlIgRAGIgQAGIARAEQBVAVArAOQBHAVA1AaQBPAnB4BKQAZAQgBAIQgBAIgeAPQg8AchUAZQiIApiqgBQggAAgxgEIhQgGIgIAAIADAIQA3BKAyBlQAgBDAxB4QAcBHASBVQAQBFAKBbQACAMgFADQgDACgLgDQjUhEiWiAQgnggg1g0IhYhWIgIgGIABAJQAuCtgzDFQgGAUgPAlQgFAQgKgMIhEhPQgmgtglhBQgRgegshZIgPglIgFgHIgDAIIgcBGQgRAqgQAbQAlATAeAOIgKgBIgIAAIgJABIANAIQBvA/BrBjICCB5QAMALgCAEQgDADgSADQhEAJg5ADQhBADg9gEQhYgMiJgZIgngJIANALQCCBoBIBIQAwA3BdBwQASAVgFAGQgGAFgkgDQhbgMhfgUQjAgxiThTQg0gchjhEIgIgEIgCAGQgBBQgRBUQgOBHgeBaQgbA/gmA5QgjAzgyA5QgGAHgGAAIgCAAg");
	this.shape.setTransform(9.9,-15.4,1,1,0,0,0,-0.2,-0.1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-233.6,-239.4,487.4,448.1);


(lib.Анимация12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhkCTIAAklIA1AAIAAD2ICUAAIAAAvg");
	this.shape.setTransform(57.1,2,0.304,0.304,0,0,0,0.5,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgZCTIAAklIAzAAIAAElg");
	this.shape_1.setTransform(49.3,2,0.304,0.304,0,0,0,0.4,0);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrCUQgtgKgfgdIAhgoQATAUAbAKQAaAJAagBQAYgBAPgJQAUgMgEgVQgCgTgbgLIgrgLQglgJgQgHQgegKgNgVQgSgfANgkQANgjAigOQAogRA0AJQAvAHAgAgIgfAnQgZgagkgGQgpgJgZARQgOAJACAQQAAAQAOAJQALAHATAFIAeAIQAvALAXAOQAgAXACAmIAAADQAAAjgYAXQgVAVgkAFQgUAEgTAAQgWAAgVgFg");
	this.shape_2.setTransform(41.4,1.9,0.304,0.304,0,0,0,0.3,0);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("ABgCTIgXg0IiSAAIgVA0Ig7AAIB9klIA7AAIB6ElgAA1AvIg1iBIAAAAIg2CBIBrAAg");
	this.shape_3.setTransform(31,2,0.304,0.304,0,0,0,0.2,0);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AA+CTIhGhaIhCAAIAABaIg1AAIAAklICGAAQAmgBAbAUQAeATAIAkQAJAngPAhQgQAkgkAOIBMBhgAhKAKIBKAAQAaABAQgPQARgQAAgZQAAgZgRgPQgRgOgZAAIhKAAg");
	this.shape_4.setTransform(20.2,2,0.304,0.304,0,0,0,0.4,0);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah3CTIAAklICDAAQAdAAAWAKQAaAMAJAYQAKAbgKAaQgLAagbALQAhAIARAaQARAcgKAiQgIAegfARQgaAOgjAAgAhBBmIBNAAQAWABAPgLQARgNABgUQABgWgQgMQgOgNgXAAIhQAAgAhDgcIBLAAQARAAALgKQAMgKAAgQQABgTgMgKQgMgKgSAAIhKAAg");
	this.shape_5.setTransform(9.3,2,0.304,0.304,0,0,0,0.4,0);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgGBzQgpgDgbgYQgagWgJglQgIgiALgiQAMgjAegUQAdgUAkAAQAqAAAfAZQAfAaAGApQAHAigMAhQgNAjgeASQgcARgiAAIgHAAgAgChGQgXACgPAOQgPAPgEAXQgEATAGAVQAGAVAQANQAQAMAUAAQAZAAARgQQAQgQAFgaQADgTgHgUQgHgWgRgMQgPgJgRAAIgGAAg");
	this.shape_6.setTransform(-6.3,3.2,0.304,0.304,0,0,0,0.3,0.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgqCRQgvgQgQg2QgOgyAUgsQAKgWASgPQASgPAXgEQAcgGAXAJQAcAJANAXIAAhtIAyAAIAAElIgxAAIAAggIgBAAQgPAaggAIQgNAEgMAAQgQAAgQgFgAg0ADQgSAoAWAkQALARATAHQASAHATgFQAUgGAMgRQALgQAAgUIAAgUQAAgYgQgQQgQgSgYgBIgGAAQgkAAgQAkg");
	this.shape_7.setTransform(-16.2,2,0.304,0.304,0,0,0,0.3,0);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("ABOB9IibjJIAADJIgbAAIAAj5IAaAAICcDKIAAjKIAbAAIAAD5g");
	this.shape_8.setTransform(56.9,18.7,0.304,0.304,0,0,0,0.5,0.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgICBQgrgDgcgaQgcgZgJgqQgIglALgnQALgnAggYQAfgXAnAAQAuAAAiAeQAhAeAGAuQAGAmgNAkQgOAnggAVQgeATgkAAIgIgBgAgEhnQghACgWAVQgWAVgHAiQgGAeAIAeQAJAfAXATQAYATAeAAQAjAAAZgXQAYgXAGgkQAFgegJgdQgKghgZgRQgXgQgcAAIgEAAg");
	this.shape_9.setTransform(46.2,18.7,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgMB9IAAj5IAaAAIAAD5g");
	this.shape_10.setTransform(38.4,18.7,0.304,0.304,0,0,0,0.5,0.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgMB9IAAjfIheAAIAAgaIDUAAIAAAaIhcAAIAADfg");
	this.shape_11.setTransform(31.1,18.7,0.304,0.304,0,0,0,0.4,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgMB9IAAj5IAZAAIAAD5g");
	this.shape_12.setTransform(24,18.7,0.304,0.304,0,0,0,0.3,0.2);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AhuB9IAAj5IBfAAQAvAAAkAbQAeAZAJApQAJAlgNAmQgMAngjAWQggATgnABgAhSBjIBDAAQApABAbgdQAcgcAAgrQAAgogcgdQgbgcgpAAIhDAAg");
	this.shape_13.setTransform(16.4,18.7,0.304,0.304,0,0,0,0.3,0.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AhSB9IAAj5ICiAAIAAAaIiGAAIAABTIB1AAIAAAXIh1AAIAABbICJAAIAAAag");
	this.shape_14.setTransform(6.4,18.7,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AhuB9IAAj5IBfAAQAvAAAkAbQAeAZAJApQAJAlgNAmQgMAngiAWQggATgoABgAhSBjIBDAAQApABAcgdQAbgcAAgrQAAgogbgdQgcgcgpAAIhDAAg");
	this.shape_15.setTransform(-8.6,18.7,0.304,0.304,0,0,0,0.2,0.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AhSB9IAAj5IChAAIAAAaIiFAAIAABTIB1AAIAAAXIh1AAIAABbICJAAIAAAag");
	this.shape_16.setTransform(-18.6,18.7,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgNB9IAAjfIhcAAIAAgaIDTAAIAAAaIhcAAIAADfg");
	this.shape_17.setTransform(-27.9,18.7,0.304,0.304,0,0,0,0.3,0.1);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgNB9IAAj5IAaAAIAAD5g");
	this.shape_18.setTransform(-35,18.7,0.304,0.304,0,0,0,0.4,0.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("ABjB9IgPjEIgBAAIhTCaIAAAAIhTiaIAAAAIgRDEIgbAAIAVj5IAaAAIBQCaIBQiaIAbAAIAVD5g");
	this.shape_19.setTransform(-43.4,18.7,0.304,0.304,0,0,0,0.4,0.1);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgNB9IAAj5IAaAAIAAD5g");
	this.shape_20.setTransform(-51.7,18.7,0.304,0.304,0,0,0,0.3,0.2);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AhSB9IAAj5IAcAAIAADfICJAAIAAAag");
	this.shape_21.setTransform(-58.2,18.7,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AAAgCQADACgDADg");
	this.shape_22.setTransform(12,-8.3,0.304,0.304,0,0,0,0.4,0.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("Ag4A2QgIAAgEgEQgDgDAAgIIAAhHQACgRAUAGIAFAAIADgCQACgBARAAIATgCQAEgCADABIABACIACACQAAgFAHAAIAKABIARgDQANgCACAFQACgCAFACQAEABABADIgBAGQgBADAFABQAAgFABgBQABAIgBANQgCAQABAEQAAAGgCAjIgDgFQgBgBgBgBQAAAAgBAAQAAAAgBAAQAAAAAAABQgBACAEAFQAAACgFADQgHADgLgBIgTgBQgLAAgbAEQgTACgOAAIgIAAg");
	this.shape_23.setTransform(37.6,-15.1,0.304,0.304,0,0,0,0.5,0.2);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AhKA2QgLgHAKABIgCgFIgCgGIAAgIIABgIIACghQABgQAEgHQAFgIAUgCQAZgEAvgEIAGgBIAFACIAIgCIAFAAQABAAAAABQABAAAAAAQAAAAABABQAAABAAAAQAGAAgCgGIAMACQADABAFAKQADAHgBAJIgCAPQgBAPADAUQADALgCADQgBADgFACQgDABgDAAIAAAAIAAAAIgBAAIADACQgGgBgJACIgVAAQgIAAgjAFQgeAGgRABIgFABQgHAAgGgEg");
	this.shape_24.setTransform(-22.8,-14.7,0.304,0.304,0,0,0,0.1,0.2);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AhABDIgIgWIgGgTQgHgaAHgOQADgGAHgCIANgBQAQAAALgFQAcgNAIgSQAGgOAMgCQANgCAIAGQAIAFAEAOIAGAXQACALAIAKQALAKgGAHQgYAdgSANQgeATgbADQgQAEgIAAIgDAAQgNAAgFgKg");
	this.shape_25.setTransform(-49.3,-9.4,0.304,0.304,0,0,0,0.4,0.1);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AhIA5IgDAAIgBgBIADAAQgQAAgBgUIACgfIACgZQADgTAGgEQAFgEAUABIALgCQAIgBAFABQgFADABABIAIgFQAEgCAKAAIA7gDIAIgBQAEAAABAEIAGgEQAEgCAEACQAFAEAHAIQgHgBAAAFQAGAAABALIgBAQQAAAYgDANQAAAAABABQABAAAAAAQABgBAAAAQAAAAABgBQAGAMgEAFQgCADgLAAIgzACIgxAGIgvAFg");
	this.shape_26.setTransform(-22.2,-20.4,0.304,0.304,0,0,0,0.3,0.2);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AAzBMQgHgCgIgHIgOgMQgagVgQgDIgXgDIgPgCIgHAAIgBAAQgLgEgFgDQgKgGAFgOIAFgbQACgRADgKQAEgNAFgFQAGgHAMACIAYAGIAaAGQAKADAOAHIAYAMQAaAMAMASQAHAKgGANQgIAVAAAFIgDAbQgBAOgBAAQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQAAAAgBAAQAAAIgIAAQgEAAgIgDg");
	this.shape_27.setTransform(-49,-19.3,0.304,0.304,0,0,0,0.5,0.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AhdAtQgCgFABgIIACgNIABgTQAAgLACgHQABgMADgGQAEgGAIgCQAKgCAkgDIAhgEIANAAQAGADAAACQABgEADgBIAJgBIAVAAIASgBQALAAAEAFQADADAAAFIgBAJIgBAVIgDASIgCAJQgCAGABADIACgEQADAEABAFQABAGgCADQgGgDgGAAIAHAHQgEACgCgBQAAgBgBAAQAAgBgBAAQAAAAgBgBQAAAAgBAAIgEABIgGACIgPACIgPAAIhCAHIgEAAQgSADgMABIgFAAQgWAAgDgLg");
	this.shape_28.setTransform(-9.9,-9,0.304,0.304,0,0,0,0.3,0.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AhHA5IgKgCQgHgBgCgCQgEgDAAgGIABgLIACgoIADgTQACgLAHgEQADgCAGAAIAIAAIAYgDIAUgDIASgBIAYgBIAYgCIAVgCQAMAAAHAGQAEACAAAFIAAAJIgBAvQgBAIAFAOIgGgDQgCgCgDAGQAHAAAEACQgHAHgSAAIgbAAQgUAAgkAEIgdAFQgQADgKAAIgDAAgAA0gyIAEAAQAAgBAAAAQAAgBAAAAQAAAAgBAAQAAAAgBAAIgEAAQAAAAAAABQAAAAAAAAQABAAAAABQAAAAABAAg");
	this.shape_29.setTransform(-9.9,-20.4,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgSBgQglgDgTgDQgPgCgGgKQgCgFACgHIAEgLQAGgPAIgKIAHgKQAFgHAFABQABgIAIgHIAMgQIAKgTIAJgJIABgBIAAAAIAAAAIABgBIAAgBIgBgFIAAgDIAPgaQAEgIADgCQAIgGAPAFIAJAEQADABAJAAQAKAAAWAFQAPACACAJQADAKgIANIgOAVQgMASgFAKIgOATIgIANIgIAIQgJAJgJAOIgGAMIgGANQAAAGgGACIgFAAIgHAAg");
	this.shape_30.setTransform(0.7,-14.6,0.304,0.304,0,0,0,0.3,0.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AhYA6QgLgBgEgFQgDgEAAgTIABgcQAAgRABgGQADgPAIgFQAEgCAHgBIAMAAIAbgDQAogEASAAIAbgCIALACIAKAAQAFgBAJgEIAQAAQAPAEgDAjQgBAJAAAQIgBAIQgBAEABADIADAHQACAEgCADQgFAGgRAAQABgBABgBQABgBAAAAQAAgBgBAAQAAABgBAAIgIAEQgDACgFAAIgGgBQgQACgeAAIgsAGIgvAEIgBABIgIABIgFAAg");
	this.shape_31.setTransform(-9.8,-14.6,0.304,0.304,0,0,0,0.2,0.2);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAhCGIgaAAQgOgBgKgEIgCAGIgDgFIgFgBIgEgCQgBAAAAgBQAAAAgBAAQAAgBAAgBQAAAAAAgBIAGAAIgGgLQgBAAAAABQgBAAAAABQAAAAAAABQAAABAAAAIADAGQgFgCgBgEQgCgEAEgDQgIgDACgNIACgKIABgKQgCgFABgCQAEgCAAgBIgEgDIgDgHIgBgOIgCgNIgCgNQgGglgBgRQgDgpADgOIADgNIADgNIAAgJQABgEAFAAQADgBAGADIAJAEQAHACANAHQAFADAPAFQAPAEAGAGQgBgBAAAAQAAgBgBAAQAAgBAAAAQAAgBAAAAQAGAFABAIIgBAOQgBAVABAVQAAAGAFAfIAGAoQAEALgDAJIAAAGIADAGQADAGgBAKIgBARIABAMQABAHgBAFQgDAHgIAAQgGAAgHgCgAAHABQAAABAAABQAAAAAAABQAAAAABAAQAAAAABAAQADgCgDgCg");
	this.shape_32.setTransform(17.5,-11.6,0.304,0.304,0,0,0,0.5,0.1);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("ACqA1IgNgDIgPgBQgMgEgFAAIgIABIgLgCIgLgCIADABIgtgDIgZABQgPABgJgCQAAADgJAAIgmADIg2AFIgbACIgbABIgXAAQgNgBgLgEQgQgIAPgcQAUgcADgHQAEgNAGgEQAEgEAFAAIAJABIAVgBQAMAAAEAIQABgBAAAAQAAAAAAAAQABgBAAAAQAAABABAAIADACQAAgFgDgEQAIABAIgBIAJgBIAIAAIAigCQAYAAALgDQAFgCAYgCQA7gDAQACQAyAEAcAAIgCAGIAOgDQAGAAAGAEQAJAGgDAWIgCAJIgCAHQAAAPgCAIIgCALIACAGIAAAEIgFAAIgBAJQgHACgFAAgAAsAhQgBAAgBABQAAAAgBAAQAAAAgBABQAAAAAAABIAIgBQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgCAAgABNAWIAAABIABABIABgCIAAgDIgCADgAiKAUQAHgBgCgCIgFAAgAhOAHQAAgBAAAAQAAAAgBgBQAAAAgBAAQAAgBgBAAQgBgBgBAAQAAAAgBAAQAAAAAAABQgBAAAAABIAHACIAAAAgAAUgdIACgEIgDgEIAAAGIABAAIABABIgBAAIAAABgAh9gfIABgBIAEgDIgGAAgABzgwIAFAAQAAgBAAAAQAAAAgBgBQAAAAAAAAQgBAAAAAAIgFAAQAAAAAAABQABAAAAABQAAAAAAAAQAAAAABAAgABiArIAAAAIAAAAg");
	this.shape_33.setTransform(1.3,-9.1,0.304,0.304,0,0,0,0.2,0.2);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AARA2QgQgCgeAAQgOAAgggCQgegCgRAAIgTgBQgHgBgPACIgWABQgPgDgGAAIgCAAQgIAAAAgLIABgSQACgcACgFIAEgOQACgNACgCQAFgHAOAAIAXAAQAzgCAKAAIAeABQAKACARAAIAeADIAQACIBAAAIAQgBIARAAQANACAOgCIAegCIANgCIANgCQALAAAFACQADABACADIAEADQAAAAAAAAQABABAAAAQAAABgBAAQAAABAAAAQAGAAADAGQAAABAAABQAAABAAAAQAAABAAAAQgBAAAAgBIgEgDQADAJgCAEIgDAGIgCgBQgDACAAAFIAAAHQAAACgDABIgEAHIAAAIQABAEgBACQAAADgDAGIgDAIIgCAHQgBADgEABQgCABgFgBQgFgCgDAAIgHAEQgEABgCgGQgDAEgDAAIgIAAIgFAAIgDgGQgEAHgKABIgRAAIgtABIgfACIgLgBgACiAbQAAABABABQAAABAAAAQABAAAAgBQAAAAABgBQAAgBgDgFQgCABACAEgADBAEIACgCIAAAAQAAgCgFgCQAAACADAEgAgpgHQgFAEAFAAQACABABgFIgBAAIgBAAIgBAAgAB9ggQgBABAAAAQAAAAAAABQgBAAAAABQAAAAAAABIAHgDIgEgBIgBAAg");
	this.shape_34.setTransform(1.6,-20,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgbDwQgDgBgBgEIABgEQAAgBAAgBQAAAAAAgBQAAAAAAAAQAAgBgBAAIgEgBIgEgDIgDgCQgBAAAAAAQgBAAAAAAQAAAAgBAAQAAAAgBAAQgBgFgEAEQgBgOgCgCIAAAAIAAgBIAAgBQAAgCACgCIAGgIIgIgDIAFAAIgBgHQAAgCgDgDIAFAAIABgEIAFgFIgHACQgDgBAAgGQADgEAAgCQABAAgCgFIABgBIgBgFIgBgIIABgRIACglIAAgbIABgEIADgBQgDgBAAgEIAAgHIAAgTQABgRAEgbQACgRAAgkIgCiJQgDgLABgGQAAgHAMgBIASACQAOABAbAJIgDAEQAIgBABAEIAAALQADAAADgFQANAiACA2IABAvIgBAvQAAAPgDAcQgDAfAAAQIgBAxQAAAUgBADIgEAGQAAAAAAABQAAAAAAAAQAAAAABAAQABAAABAAIAAAZIgDgCQAAAAgBgBQAAAAAAAAQgBABAAAAQAAAAAAABQgBADAEAFIgCAHIgBAHQAAABAFAAQgDADAAADIAAAGIgDgEIgCgEIgCgDIAAADIgBAFIgEAEIAHAHIADgEQACADgFAGQgGAGADACIACgDQAEACAAADIAAAIQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAgBQAAAAABgBIgKACQABABAAAAQAAABABAAQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBAAAAABQAAAAAAAAQAAAAAAABQAAAAABAAQAAAAABAAQABgBAAAAQAEgCACACQgBABAAAAQgBAAAAABQAAAAAAABQAAAAAAAAIADAFQgDADgDgCIgGgEIgBAHQgGgBgDgDIgDgEQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAABgBAAQABAAAAABQAAAAABABQAAAAAAABQAAAAgBABIgDADIgBgGIgCADQgBgDgDADQgDACAGACQAAABAAAAQAAAAAAAAQAAAAgBAAQAAAAgBAAIgEgBIgEAAIgMgCIACAFIgHgBgAgbCmQABAAABAAQAAABABAAQAAAAABgBQAAAAABAAQgCgCgGAAQAAAAABABQAAAAAAAAQABABAAAAQABAAAAAAgAAcCjQAHgBgDgFQgDAGgGgEQgCAEAHAAgAAlBjQABAAAAgBQABAAAAgBQAAAAAAAAQgBgBAAAAIgEgCIgFAAQAGAGACgBgAABA2QABAAABABQAAAAABAAQAAgBABAAQAAAAABgBIgGgDIAAABIAAAAIAAAAQAAAAAAABQAAAAAAABQAAAAAAAAQABABAAAAgAAkiIIACgDIgEgEQACADAAAEgAAhjKIAAABQAAABABABQAAAAAAAAQABABAAAAQAAAAABAAQADgBgCgEIgBgCQAAAAAAAAQgBABAAAAQAAAAgBABQAAAAgBABg");
	this.shape_35.setTransform(42.8,-15.1,0.304,0.304,0,0,0,0.4,0.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAWDdQgDgEAAAIQgSgCgHACQgQACgGgEIAEgCIgIgDIADgCIgEgCIgDgBIACAIQgHgCgCgKQgCgKAEgFIADACQAAgFgEgCIgGgCQgFgGAJgEIgDgBQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBAAAAIgBgVIAGADIAAgKQgGADAAgDIAAgJQAAgGgCgCIgCgIQgCgSAFgFQgGgDAEgZIACg5IABgaQAAgFACgIIACgCIgCgEQgBgFACgNIACgWIABg2QgCghABgRIABgMIgBgLIgCgIQgBgEACgDQAEgFAOAAIASgBIAUgBQANAAAJgCQAJgDAEABQAGACACAIQABAEAAAXIABA0QACA3gGAxIgDALIADAFIABAIIgDAmIgDAuQgBAGABAMQABAMgBAGIgBAIIABAEIgBAKIABAZIABAdIAAAQQAAAAgBABQAAAAgBAAQAAAAgBAAQAAABgBAAQAFAFgBAJIgEgDIgFACIABgHQgFAAgDADQgBAAAAABQAAAAAAABQAAAAAAABQAAABABABQAAADgBACIgDABQgDAAgCgFgAArC6QAAAAAAABQAAAAABAAQAAABAAAAQAAAAABABIABgFIAAAAIgBAAQAAAAgBAAQAAAAAAAAQAAAAAAABQgBAAAAABgAgmC0QAAABAAAAQAAABAAAAQABAAAAABQABAAABAAIACgEIgFgDIABACIgBgCIAAAEgAAnClQAAABAAAAQAAAAAAABQAAAAAAAAQAAAAABABQAAAAAAAAQABABAAAAQAAAAABAAQAAAAAAAAIABgCIgCgFIgCADgAAoCIIgBABQgBAAAAABQAAAAAAAAQAAABABAAQAAAAABABQADABgBgDIgCgEQgBAAAAABQgBAAAAAAQAAAAABABQAAAAABAAgAguCLQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABAAIgCgEQgBAAAAAAQAAABAAAAQAAAAAAABQAAAAAAABgAgrBfIADgFIgCgBQgCADABADgAgjBWIADADQAFgCAAgBIgEgCIgEACgAATA4QgBAAAAABQgBAAAAAAQAAABAAAAQAAAAAAABIADAAQABAAAAgBQABAAAAAAQAAAAAAgBQABAAAAgBQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAgBAAIgCACgAggAtQgDACAEABQAEAAACgCIgFgCIgCABgAglguIgBAGQAGgBAAgDQAAgBAAAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgCgBIgBABg");
	this.shape_36.setTransform(10.8,-15,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgeDuQgEgFgCgGIgHgJIABADQgHgKgBgLQgBgHAAgRIAFgzIABhAIABgDIgCgCIABgcQAFh8gGhWIAAgZQgBgOgCgKQgCgLADgDQAEgEAOAAIAvgBIATAAQAKADACAJQACAKAAAQIgCAaQAAASAEAhQABAXgCBOQgDBVgBASQgCARAAAkQAAAigCASIgKgBQAAABAFADQAEACAAADQACANgCANIgCALQgCAFgFACQgLACgFADIgKADQgHADAAADIgBAHQgCAEgDAAQgLAAgNgNg");
	this.shape_37.setTransform(-28,-14.1,0.304,0.304,0,0,0,0.2,0.1);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AgMEBQgFgDgGAHQgDgGgGgCIgLgIQAEgBACgFIgCABIgCABIgCgCQgDAGgDgKQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBIABgEQgEgGABgFQgBAAAAAAQgBgBgBAAQAAAAAAgBQgBAAAAgBIAAgFIAAgOIABgbIAAgUQAAgOAGgFQgFgEAAgNQgCgQACgHQACAEAAgGIACABIgCgDIgDgEQgBgBAAgKIgCheQgCgZAAgxIgBgjIAAgLQAAgKAFACQgEgCgBgCQgBgBAAgIIAAgZQgCgOABgHQACgEAAgDIAAgGIgCgFIgBgWQgCgJACACQAFgDAKABIAEgCIAFgBIAlABQAKAAAIACIAZAFQAOAEACAMIABANIgBANIABAkIADC4IgBANIACASIACAiIgBALIABAIIAAAJIgBAFIgBAFIACAFIABAFIAAAhIgCAhQAAAVgGABIAEAFQACAEAAACQAAACgEACQgDADgBACQAAABAAAAQAAABAAAAQAAAAABAAQAAAAABAAQAAgBABAAQABgBAAAAQABAAAAAAQABAAAAABQADADgEADIgHAEIAFACQAAAAgBABQAAAAAAABQgBAAgBAAQAAAAgBAAIgFABQgGAFgFABIgRADIAAAAQABACgHAAQgGAAgJAKIgBgDIgEAEQgDgGgEgCgAAYDxIgFADQgIABgDAEIAHABIABAAQAAgDAGgCQAGgCADABQABgBAAAAQAAgBAAAAQAAAAAAAAQAAgBgBAAIgEACIgDgCIAAAAgAAwDsIABABQAAgBABAAQAAAAAAAAQAAAAAAgBQgBAAAAAAgAg3jGIAAABQAAAAABAAQABAAAAAAQAAgBAAAAQAAgBgBAAIgBABg");
	this.shape_38.setTransform(33.5,-14.2,0.304,0.304,0,0,0,0.5,0.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgHEGIgOgKIAEgFQACgDgDgDQgDAGgBAAQgBAAgDgFIgDgEIgFgEQgEgDgCgMIgDgMQgBgGABgKIAAgRIABABIgCgGIgCgEQgBgEADgGIADgDIgCgEIgDgKQgEgNACgSIABgPQABgJAFgFQgHgBAAgIIAAgOIAAgtQAEABgCgEIgCgHQAAgKgCgGIgBABIAAgyIACgIIADgIIgCABIgCACQgCgSAGgKQgEACAAgJIAAgNIAAggQAAgqACgUIAAgXQABgPAJgFQAFgCAFAAIAJABIAMAAIAMACIAWABQAOACAEAIQADAHAAANIgCAUIgBBfIABAJIgBAHIAAACQgEAAgBACIAEAFQABACAAAEIABAtIgCASQABARAABSQgBAAgBgBQgBAAAAAAQAAgBAAABQAAAAAAAAIADAGQACAEgBAHIgBAKIABAZIABANQAAAHgCAEQABAAABABQAAAAABAAQAAABAAAAQAAABAAABIgBAHIACASQADAYgCAHIgCAFIABADQADALgBAEIgEAIQgDAFgDABQgCABgFgBQgEgCgCABIADAEIgMgBQgHAAgFADIgDADIgEABIgCgCQgBgBAAAAQgBAAAAAAQgBAAAAABQgBAAgBAAQACAAAFAEQAFADgBABQAAABAAAAQAAAAgBABQAAAAgBAAQAAAAgBAAQgBAAgHgEg");
	this.shape_39.setTransform(-15.8,-13.6,0.304,0.304,0,0,0,0.3,0.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAAABIABgCIAAADg");
	this.shape_40.setTransform(56.1,-11.1,0.304,0.304,0,0,0,0.3,0.3);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgJBtIgSgGIgIgFQgFgDgDAAIgLgCQgCAAgCAEIgDAGQgEgHgDAAQgCgBgFACIgHACIgHAAIgEgEIgGgBQgDABgBgDQABgHgDgBIgIACIgFgCIgJgIIgDgDIgDACQgDAAgCgCIgFgEQgDgDgCACIgBAAIgCgCIAAgCIgDAAIgEgBIgHgGQgagVgKgOQgUgegJgbIgJgaIgDgKQgBgEAGgEQAGgFAUgJQASgIAJgCIAXgHQAOgBACAOIABAIIAGAGQAEAGAFANIAQAcIAIAJQAFAFgCAFQAEgBABACIAEAEQACACAGACQALAFAMAKQACgFANAJIAQALQAQAGAKgBIAFgBQAAAAAAAAQABgBAAAAQABAAAAAAQAAgBAAAAIgCAAIAAgBIAGgBQADAAABAEQACgHALgDIAQgIQAAAEABABIAFABQgBgBAAAAQAAgBAAAAQgBgBAAAAQAAgBAAAAIADgCQAEgEACAAQABAAABAAQAAAAABAAQAAAAABAAQAAAAAAABIACAEQACgJAFgBIALgEQAHgCADgDQACAGABgCIADgGQADgGAIgGIACADIACACIABgCIgBgCIABgFIAXgaQAGgHAEgSQAEgTAGgHQAGgIARAGIAYAIIALADIAIABQAEAAAGACQAGADACAEQAGgEABAIIABAHIgFAIIgDANIgGAQIgDAJQgCAGgCAEIgJANQgHAOgDAEQgSAVgQAIQACgIgDAEQAAAAgBAAQAAABAAAAQAAAAAAABQgBABAAAAIAAAEQgBADgGAEQgOAEgEAEQgLAIgVAIIgnASQgcAIgOAGQgLAEgMAAQgGAAgIgCgAAfAgQAEgEAAgBIgDgFIgBAKgAByAXIgCADIABACIAAABIAGgHIgDgCIgCADgAAsAcIgBgDIAAAAQABAAAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIAEgGQgBAAAAAAQgBAAAAAAQgBAAAAABQgBAAAAABIgBADIAAAAIAAABIABACIAAAAgACaAbQAAgBAAAAQAAgBABAAQAAAAABAAQAAAAABAAIgEgDQgCACADADgAgzAWQAAABAAAAQAAAAABABQAAAAAAAAQAAAAABABQABAAAAAAQABgBAAAAQAAAAAAAAQAAgBAAAAIgCgBIgCAAgAhTgCIACADQAAgBABAAQAAAAAAAAQAAAAAAAAQABAAAAAAIgBgCIgCgBIgBABgADbgZIACAEIABAAIABgCQABAAAAgBQAAgBAAAAQAAgBAAAAQgBgBgBAAIgCgBQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAAAABgAiCgsQACAHADgBQAEgBgEgGIgGgIIABAJg");
	this.shape_41.setTransform(53.4,-10.8,0.304,0.304,0,0,0,0.3,0.2);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("ACgB4QgDgEgDgHIgFgMQgIgNgEgMQgBgFgLgOIgHgKIgJgJIgTgPQgMgJgKgBIgJgDIgHgDIgKgBIgJgDQgWgMgbgGQgRgEgJAAQgPgBgLAFQgPAGgZAXQgTATgHAWIgHAaIgFAaQgDAIgDADQgEADgJAAIgYgFQgQgDgMgEQgQgEgEgDQgKgHACgLIAHgUIAFgZQADgPAFgKQAKgXASgTIAcgbQALgJAfgPIALgFIAKgEQAIgGABAHQABAAAEgIQADgDAMgCIAMgDQADgCADgFQADgFADgBQAEgCAGABIAKABQAIgBAQACIAKgCIAMgCQAHABAMAJIAzAZQALAEAKAGIAXANQAcALAOANIAHAIIAGACQAKAJgGADIAJACQAEACgDAGQAIgBAIANIAKAVIAEAMIgBADIADADQAIAIAEAOQAAgBgBgBQAAAAAAAAQAAAAAAABQABAAAAACIAAgBIAEALIACAKQgBAMgNAHQgGAEgEABIgGABIgFgBQgKAAgFAFQgKAIgHACIgGAAQgJAAgEgEgACiB4QADAEACgFIgFgCgACyAtIAHABQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBgBAAAAQgDAAgCACgAjDACQAAABAAAAQAAABAAAAQABAAAAABQABAAAAAAIACgFQgBAAAAAAQgBAAgBAAQAAABAAAAQgBABAAAAgAh2hTIADACIAEgCIgEgBIgBAAIgCABg");
	this.shape_42.setTransform(53.4,-18.4,0.304,0.304,0,0,0,0.2,0.2);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("ABGD3IgRgGQgWgHgNgHQgggRgbgfQgKgLgMgVIgTgiIgXgjQgIgPgHgUQgLgjAEgqQAFghADgJIAQgkQAHgSAOgQIAKgMQAHgIAFgDQAIgFAPgPIAagZQAMgKATgGIAkgKQAOgDAagDQAKgCARAMQABABgBAAQgBAAAAAAQgBAAAAAAQAAAAgBABQAAAAAAAAQALAGgDASQgBAIgHASIgDANQgBAEgDACIgFAEIgGAIQgDAEgFAAQgMAAgGACQgSAFgRARIgNAMIgMAMQgDAEgIAGIgDACIgBAFQgBADgDAEQgDAEgBAEIgBAIIgBAGQgCAGgIAHIgEAQQgCANAEAWQABAGAFAKQAFAKABAFIAEATQACAKADAHIAGANQADAJAEAEQAJAOALAHIAQAKIAQAGQALAGAXACQAJAEABAGIAAAEIgCAEIgCALQgCADAAAHQAEAGgBAEIgFAJIgDAMQgFAUgHAGQgFAEgHAAIgEAAg");
	this.shape_43.setTransform(-56.8,-14.3,0.304,0.304,0,0,0,0.2,0.2);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AC0DhQgFgCgEgDIgHgHIgRgQQgIgGgGgMIgCAFIgugkIgngZIgugcIgLgHQgJgFADgEQgJABgLgLIgWgRQgNgJgNgLIgKgIQgFgGACgFQgFACgFgEIgCgEIgCgEIgKgDIg8hDIgXgbQgKgNAAgFQAAgIACgMIAEgTIAGgjIAEgOQAEgIAGgCQAJgDAOAOIAWAWIAWAXQADAEAIAFIAGAJIAUAXQAKALAQAOIAbAYIA1AoIAYAPIALAFQAFADgCAEQAGgDAHACIALAIIAKAGQAGAEAFABQACgJABgMIAAgTQACgNAAgcQACg5gCgcIgFgoIgGgZQgBgPARAAQAKAAARAEQAfACAOAMQAJAHAAAMQAAAFADAEIAEAKQADAPAAAOIACAQQABAJgBAHQgBAIACATIgDAZIACADQACAJgBAPIgCAZIgDA2QAAALgCAHQgEgEACAEIACAIQABAFgCALQAAAIAEAHQAFAGgCAEQAGABABAGIAAAQQACAMgFAVQgBADADAGQAEAJgCAJIgDALIAAAHQgBACgFAAQACAFgMABIgEAAIgMgBgACNC3IAAADQABAAAAAAQAAAAAAAAQABAAAAAAQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAgBAAIgBABgAhIAiIgCACIACACIADgDIgCgBIgBAAgAiFgRQADABAEgCIABgCIgFAAIgDADg");
	this.shape_44.setTransform(22.3,-15.3,0.304,0.304,0,0,0,0.4,0.2);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("ACYD+QgIAAgCgBIAEgCQAAgBAAgBQAAAAAAAAQgBAAAAAAQAAAAgBAAIgDABIgCgFIgCgFQgFADgGgXQgJgSgDgKQgCACgFgMIgHgOQgEgHgQAAIgOABIgPACIg5AEQgIAAgEgCIgEgDIgFAAQgDgBgEgEQgDgEgBgEQAAgEADgHIAEgLIAIgcQAMghARgBQAMgBAXABIAIgBQAFAAACgCQADgCgBgDIgDgGIgVgwQgNgjgLgPQgRAZgTAhIggBAIg7B5IgRAgIgFALQgDAGgFACQgDABgTAAIgbgBQgygEAEgUQABgFAGgJIAIgMQAJgQAFgNQAOghAPgfIAJgSQAEgJgBgKIAHgMIAEgHQACgCAEABQgFgFAHgMQAJgMADgJIAFgIQAAgBABAAQAAAAAAAAQABgBAAAAQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABgBAAAAQABAAAAAAQAAAAAAAAQAAAAgBgBIgBgDIAEgKIAIgRQABAAABgBQAAAAABAAQAAAAAAAAQAAAAAAAAQADgEAAgQQAAgOAFgEIAKgFIAIgKQANgPANgWIAMgTQAIgMgCgIQAAgFgJgKQgHgIABgGQACgHAHgIIAMgNIAbgcQAHgHAFAAQAEgBAGAHQAJAJAMASIAOAUIAIARQANATAHAVIAHAUIAKATIADAKQABAGACAEIALAWIATAvIAJAQIAGATIABAEIAEAFIAFANQAHAQADAEQAHAGACAHQADAHABAPQAEANAAAJQAFgFAGATIAHAPIAIAPIAEAHQABACAEABIAGABQADABACADQAEAFACAOIAFAKIAEAKQAAgBAAAAQAAgBAAABQAAAAABABQAAABAAABIAAABIgBgCIABADIADAOQACAKgGAGQgFAFgLgEIgQgGQgPgGgUALQgKAEgEAAg");
	this.shape_45.setTransform(-38.5,-14.6,0.304,0.304,0,0,0,0.2,0.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-60.8,-22.5,121.7,45.2);


(lib.Анимация11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.Machine();
	this.instance.setTransform(-68,-88,0.92,0.92);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-68,-88,121.5,173);


(lib.Анимация10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.hand();
	this.instance.setTransform(-39.9,-30.1,0.85,0.85);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-39.9,-30.1,79.9,60.4);


(lib.Анимация9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.compos();
	this.instance.setTransform(-122,-231,0.84,0.84);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-122,-231,201.6,336);


(lib.Анимация8 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EABF23").s().p("AvnLUIAA2oIfOAAIAAWog");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-72.5,200,145);


(lib.Анимация7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.BTS2016OFFER();
	this.instance.setTransform(-110,-72);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-110,-72,216,143);


(lib.Анимация6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cloud2();
	this.instance.setTransform(-91,-42,0.78,0.78);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-91,-42,152.9,81.9);


(lib.Анимация5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.cloud1();
	this.instance.setTransform(-70,-53,1.09,1.09);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-70,-53,151.5,97);


(lib.Анимация4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AGUCjQgIgCgEgCIAFgSIAKAEQAHACAIAAIAHgBIAGgDIAEgFQACgDAAgFQAAgGgFgEIgHgCIgMgCIgKAAIAAgQIALAAIAHgBQAFgBAEgDQAEgEAAgFQAAgHgFgDQgEgCgIAAQgGAAgGACIgJADIgFgRIAEgCIAHgCIASgCQAHgBAGACQAHABAFADQAFADADAFQADAFAAAIQAAAIgFAGQgEAHgJADIAAAAQAKADAFAGQAGAHAAAKQAAAJgEAGQgDAGgGAEQgFAEgIACQgHACgIAAQgKgBgIgBgAACCiQgGgDgGgHQgEgDgCgEIgFgJQgEgLAAgPQAAgQAFgKIAFgJIAGgIQAHgGAGgDQAIgDAJABIAPABIAKACIgEASQgDgCgFAAIgLgBQgHgBgFADQgFACgDAFQgGAIAAATQAAAIACAHQABAGACAGQAEAEAFADQAGADAHAAQAHgBAFgBIAIgEIAEARQgFADgHACQgIABgIABQgMgBgGgCgACOCkIgYgCIAAhpIBAAAIAAATIgsAAIAAAVIAOgBQAIAAAHACQAHACAFADQAFAEADAGQAEAHAAAJQAAAJgEAGQgDAHgFAEQgGAFgHACQgIACgKAAgACKByIAAAgIAMABIAHgBIAGgDQACgCACgDQABgEAAgEQAAgFgBgEQgCgCgDgCQgDgDgDAAIgIgBgAk+CiIAAhoIAXgCIAJAAIAOABIAMAEQAGADADAFQADAFAAAIIgBAIIgDAHIgGAGQgDACgFABIAAABIAIADIAHAEQADAEACAEQACAFAAAGQAAAIgEAGQgDAGgGADQgGAEgHACQgHACgIAAgAkqCSIACABIAHAAIAEAAIAHgBIAGgDQADgCACgDQABgCAAgFQAAgEgCgDQgCgDgDgBIgHgCIgSgBgAkqBKIAAAcIALAAIAFgBQAFgCAEgEQAFgDAAgGQAAgEgCgCIgEgEIgGgCIgGgBgAJOCjIgEgBIACgSIACAAIACABQAAAAABgBQABAAAAAAQABAAAAAAQABgBAAAAQADgBABgDQADgDABgGIADgRIADg4IA+AAIAABqIgUAAIAAhXIgXAAIgDAvIgDAQIgGANQgCADgDACIgFAEIgGACIgFABgAhpCjIgHgDIAGgQIAEABIAFAAQADAAADgDQACgDACgFIgohNIAZAAIAVAvIADAOIABAAIACgPIAQguIAVAAIgiBYIgHALQgDADgFADQgEACgGAAgANmCjIAAg7IACgNIgBAAIgHAOIgnA6IgQAAIAAhqIAVAAIAAA5IgCAPIABAAIAIgPIAng5IAPAAIAABqgAL5CjIAAg7IABgNIgBAAIgHAOIgnA6IgPAAIAAhqIAUAAIAAA5IgBAPIABAAIAHgPIAng5IAPAAIAABqgAIkCjIAAg7IACgNIgBAAIgIAOIgnA6IgPAAIAAhqIAUAAIAAA5IgBAPIABAAIAHgPIAog5IAPAAIAABqgAFmCjIgJgYIggAAIgIAYIgUAAIAmhqIAPAAIAlBqgAFZB6IgIgWIgDgRIgBAAIgDARIgHAWIAWAAgADWCjIAAhpIAdgCIAPABQAIABAHAFQAGADAEAHIADAIIABAKQAAAJgEAIQgDAGgGAFQgGAEgHACQgHACgIAAIgGAAIgDAAIgDAAIAAAkgADqBLIAAAiIACAAIAPAAIAHgEQADgCACgDQACgEAAgFQAAgGgCgCQgBgEgDgCQgDgCgEAAIgIgBgAiiCjIgggtIgFAAIAAAtIgVAAIAAhqIAVAAIAAAvIAFgCIAdgtIAXAAIgfAtIgIAGIAJAFIAjAygAmeCjIAAg7IABgNIgBAAIgHAOIgnA6IgPAAIAAhqIAUAAIAAA5IgBAPIABAAIAHgPIAng5IAPAAIAABqgAoMCjIAAg7IACgNIgBAAIgIAOIgnA6IgPAAIAAhqIAUAAIAAA5IgBAPIABAAIAHgPIAog5IAPAAIAABqgAp3CjIgfgtIgGAAIAAAtIgUAAIAAhqIAUAAIAAAvIAFgCIAdgtIAXAAIgeAtIgIAGIAIAFIAjAygAsQCjIAAhpIAdgCIAQABQAIABAGAFQAGADAEAHIADAIIABAKQAAAJgDAIQgEAGgFAFQgGAEgHACQgIACgHAAIgGAAIgEAAIgCAAIAAAkgAr7BLIAAAiIACAAIAPAAIAHgEQADgCACgDQACgEAAgFQAAgGgCgCQgCgEgDgCQgDgCgEAAIgHgBgAtACjIAAgqIgLADIgWAnIgZAAIAXgjIAJgHQgFgBgEgCQgFgDgDgEIgFgJQgCgFAAgHQAAgKAEgGQADgGAGgEQAGgFAIgCQAIgBAJAAIAGAAIAUACIAABpgAtQBLIgGACIgEAGQgCACAAAGQAAAEACAEQABADADACQACACAEAAIAIACIAIAAIAAghIgEAAgAm8AzIgJgDQgDgCgDgDQgCgDgBgGIATgDQAAAFADADQADABAFAAQAFABADgDQACgCABgFIARADIgDAIQgDAEgDACIgIADQgFABgGAAIgMgBgAAogiQgIgEgGgHIgEgIQgDgEgBgFQgDgKAAgNQAAgNADgKQADgKAGgHQAMgOAVAAIALABIAJADIAHAFIAHAGIAEAIIAEAJQADAKAAAMQAAAOgDAKQgDAKgGAHQgMAOgVAAQgLAAgJgEgAArhwQgGAJAAASIABAPQACAHACAFQADAEAFADQAEADAGAAQALAAAGgJQADgEABgHQACgHAAgKIgBgOQgCgHgCgFQgDgEgEgDQgFgDgGAAQgLAAgGAJgAlqgiQgJgEgFgHIgFgIQgCgEgBgFQgDgKAAgNQAAgNADgKQADgKAGgHQALgOAVAAIALABIAJADIAIAFIAGAGIAFAIIADAJQADAKAAAMQAAAOgDAKQgDAKgGAHQgLAOgWAAQgLAAgIgEgAlnhwQgGAJAAASIABAPQABAHADAFQADAEAEADQAEADAGAAQALAAAGgJQADgEACgHQABgHAAgKIgBgOQgBgHgDgFQgCgEgFgDQgEgDgHAAQgKAAgGAJgAFOggIAAhpIA/AAIAAASIgqAAIAAAZIAmAAIAAASIgmAAIAAAaIAqAAIAAASgAEHggIAAhXIgfAAIAAgSIBSAAIAAASIgfAAIAABXgAC/ggIAAg6IABgOIgBAAIgHAOIgnA6IgQAAIAAhpIAVAAIAAA5IgCAOIABAAIAIgPIAng4IAPAAIAABpgAhLggIAAhoIAdgDIAQACQAIABAGAEQAGADAEAIIADAIIABAKQAAAJgDAHQgEAHgFAEQgGAFgHACQgIACgHAAIgGAAIgEgBIgCAAIAAAkgAg2h4IAAAiIACABIAPgBIAHgDQADgCACgDQACgEAAgGQAAgFgCgDQgCgEgDgCQgDgBgEgBIgHgBgAh5ggIgfgtIgFAAIAAAtIgVAAIAAhpIAVAAIAAAuIAFgCIAdgsIAXAAIgfAsIgIAGIAJAFIAjAygAj6ggIAAhXIgfAAIAAgSIBSAAIAAASIgeAAIAABXgAChiPQgFgBgEgDQgEgCgCgDQgDgDAAgFIASgEQABAFADACQADACAEAAQAFABADgDQADgCAAgFIASADIgDAIQgDAEgDACQgEACgFABQgFACgGAAIgLgBg");
	this.shape.setTransform(-0.8,-1.7);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-89.9,-18.2,178.3,33);


(lib.Анимация3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#9AC8D6").s().p("AvnXcMAAAgu3IfOAAMAAAAu3g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-150,200,300.1);


(lib.Анимация2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AvnXbMAAAgu2IfOAAMAAAAu2g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-100,-150,200,300);


(lib.Анимация1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой 1
	this.instance = new lib.nespresso_logo();
	this.instance.setTransform(-79.5,-14,0.74,0.74);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-79.5,-14,159.1,28.1);


// stage content:
(lib.nespresso = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		var fixed_count = 0;
		
		fl.outputPanel.clear()
		
		// disable idle alert for big count fla data
		fl.showIdleMessage(false);
		
		// start work
		fl.trace( new Date() + ' Start.');
		
		// library
		for( var i in fl.getDocumentDOM().library.items){
			if (fl.getDocumentDOM().library.items[i].itemType == "movie clip") {
				roundTimeline(fl.getDocumentDOM().library.items[i].timeline);
			}
		}
		
		// movie
		roundTimeline(fl.getDocumentDOM().getTimeline(),"");
		
		// end work
		fl.trace( new Date() + ' End. Fixed ' + fixed_count + ' objects.');
		
		function roundTimeline(tl){
			for (var i = 0; i < tl.layers.length; i++){
				roundLayer(tl.layers[i]);
			}
		}
		
		function roundLayer(layer){
		    var startFrameIndex = -1;
			for(var i = 0; i < layer.frames.length; i++){
		        if(layer.frames[i].startFrame != startFrameIndex) {
		            startFrameIndex = layer.frames[i].startFrame;
		            roundFrame(layer.frames[i]);
		        }
			}
		}
		
		function roundFrame(frame){
			for (var i = 0; i  < frame.elements.length; i++){
				roundElement(frame.elements[i]);
			}
		}
		
		function roundElement(el){
			var elname = el.name ? el.name + " " : "";
			
			if(el.libraryItem && el.libraryItem.timeline) {
				fl.trace("Element " + elname  + "has child. LibraryItem timeline layers len " + el.libraryItem.timeline.layers.length );
				roundTimeline (el.libraryItem.timeline);
				fl.trace("Element " + elname  + "childs round done");
			}
			var mat = el.matrix;
		
			if (mat) mat.tx = Math.round(mat.tx);
			if (mat) mat.ty = Math.round(mat.ty);
		
			var rx = Math.round(el.x);
			var ry = Math.round(el.y);
		
			
			
			if(rx != el.x || ry != el.y){		
				fl.trace("Element " + elname  + "FIXED. Before: x = "  + el.x + ", y = " + el.y + " after: x = " + rx + ", y = " + ry);
				el.x = rx;
				el.y = ry;
				el.matrix = mat ;
				fixed_count ++;
			}else{
				fl.trace("Element " + elname + "OK: x = " + el.x + ", y = " + el.y);		
			}
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(389));

	// legal
	this.instance = new lib.Анимация21("synched",0);
	this.instance.setTransform(103,150.2);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(361).to({_off:false},0).to({alpha:1},5).wait(23));

	// монограмма
	this.instance_1 = new lib.Анимация20("synched",0);
	this.instance_1.setTransform(100.1,67.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(361).to({_off:false},0).to({alpha:1},5).wait(23));

	// фон черн
	this.instance_2 = new lib.Анимация19("synched",0);
	this.instance_2.setTransform(100,-159);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(351).to({_off:false},0).to({y:150},10).wait(28));

	// капсула
	this.instance_3 = new lib.Анимация17("synched",0);
	this.instance_3.setTransform(102.2,107,0.29,0.29,0,0,0,0,0.1);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(288).to({_off:false},0).to({regY:0,scaleX:1,scaleY:1},11).to({_off:true},65).wait(25));

	// cafezinho-claim2.svg
	this.instance_4 = new lib.Анимация18("synched",0);
	this.instance_4.setTransform(102.9,191.1,0.66,0.66);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(288).to({_off:false},0).to({scaleX:1,scaleY:1},11).to({_off:true},65).wait(25));

	// plants.svg
	this.instance_5 = new lib.Анимация16("synched",0);
	this.instance_5.setTransform(-83.5,110.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(288).to({_off:false},0).to({startPosition:0},8).to({rotation:6,x:-83.4},23).to({rotation:0,x:-83.5},30).to({_off:true},15).wait(25));

	// листья 2
	this.instance_6 = new lib.Анимация15("synched",0);
	this.instance_6.setTransform(10.5,-86.9);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(288).to({_off:false},0).to({startPosition:0},8).to({rotation:2},23).to({rotation:-7,x:10.6},30).to({_off:true},15).wait(25));

	// plants.svg
	this.instance_7 = new lib.Анимация13("synched",0);
	this.instance_7.setTransform(-149.7,-266.5,1,1,-98);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(274).to({_off:false},0).to({scaleX:1.17,scaleY:1.17,rotation:-97.8,x:344.3,y:428.5},14).to({startPosition:0},8).to({regX:-0.1,regY:0.1,rotation:-93,x:344.4},23).to({regX:0,regY:0,rotation:-97.8,x:344.3},30).to({_off:true},15).wait(25));

	// фон зел
	this.instance_8 = new lib.Анимация14("synched",0);
	this.instance_8.setTransform(100,150);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(286).to({_off:false},0).to({startPosition:0},63).to({_off:true},15).wait(25));

	// название
	this.instance_9 = new lib.Анимация12("synched",0);
	this.instance_9.setTransform(132.8,-27.8);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(198).to({_off:false},0).to({y:42.2},9).to({startPosition:0},65).to({alpha:0},8).to({_off:true},4).wait(105));

	// кофемашина
	this.instance_10 = new lib.Анимация11("synched",0);
	this.instance_10.setTransform(266.4,210.6);
	this.instance_10.alpha = 0;
	this.instance_10._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(198).to({_off:false},0).to({x:136.4,alpha:1},9).to({startPosition:0},65).to({alpha:0},8).to({_off:true},4).wait(105));

	// рука
	this.instance_11 = new lib.Анимация10("synched",0);
	this.instance_11.setTransform(73,108.2);
	this.instance_11.alpha = 0;
	this.instance_11._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(198).to({_off:false},0).to({alpha:1},3).to({rotation:5,x:73.7,y:104.9},21).to({rotation:0,x:73,y:108.2},17).to({rotation:5,x:73.7,y:104.9},17).to({startPosition:0},16).to({startPosition:0},8).to({_off:true},4).wait(105));

	// ж
	this.instance_12 = new lib.Анимация9("synched",0);
	this.instance_12.setTransform(122,200);
	this.instance_12.alpha = 0;
	this.instance_12._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(198).to({_off:false},0).to({alpha:1},3).to({startPosition:0},71).to({alpha:0},8).to({_off:true},4).wait(105));

	// выгода
	this.instance_13 = new lib.Анимация7("synched",0);
	this.instance_13.setTransform(100,150.1,0.71,0.71,0,0,0,0.1,0.1);
	this.instance_13.alpha = 0;
	this.instance_13._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(112).to({_off:false},0).to({regX:0,regY:0,scaleX:0.74,scaleY:0.74,y:150,alpha:1},8).to({startPosition:0},60).to({alpha:0},5).to({_off:true},13).wait(191));

	// плашка желт
	this.instance_14 = new lib.Анимация8("synched",0);
	this.instance_14.setTransform(100,150,0.36,0.36,0,0,0,0.1,0.1);
	this.instance_14.alpha = 0;
	this.instance_14._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_14).wait(103).to({_off:false},0).to({regX:0,regY:0,scaleX:1,scaleY:1,alpha:1},17).to({startPosition:0},63).to({scaleY:2.07},14).to({_off:true},91).wait(101));

	// облако 2
	this.instance_15 = new lib.Анимация6("synched",0);
	this.instance_15.setTransform(-3,558.5);
	this.instance_15._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_15).wait(38).to({_off:false},0).to({y:255.5},12).to({x:36},136).to({_off:true},12).wait(191));

	// облако 2
	this.instance_16 = new lib.Анимация5("synched",0);
	this.instance_16.setTransform(215,315);
	this.instance_16._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_16).wait(38).to({_off:false},0).to({x:216,y:21},12).to({x:173},136).to({_off:true},12).wait(191));

	// вкус бразилии
	this.instance_17 = new lib.Анимация4("synched",0);
	this.instance_17.setTransform(100,446);
	this.instance_17._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_17).wait(38).to({_off:false},0).to({y:136},12).to({_off:true},148).wait(191));

	// фон син
	this.instance_18 = new lib.Анимация3("synched",0);
	this.instance_18.setTransform(100,449.8);
	this.instance_18._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_18).wait(38).to({_off:false},0).to({y:150},12).to({_off:true},148).wait(191));

	// nespresso
	this.instance_19 = new lib.Анимация1("synched",0);
	this.instance_19.setTransform(99.6,150.1,0.49,0.49,0,0,0,0.1,0);
	this.instance_19.alpha = 0;
	this.instance_19._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_19).wait(4).to({_off:false},0).to({scaleX:0.87,scaleY:0.87,x:99.2,y:150,alpha:1},15).to({startPosition:0},13).to({startPosition:0},6).to({regX:0,scaleX:1,scaleY:1,x:99.6,y:-149.9},12).to({_off:true},53).wait(286));

	// фон черн
	this.instance_20 = new lib.Анимация2("synched",0);
	this.instance_20.setTransform(100,150);

	this.timeline.addTween(cjs.Tween.get(this.instance_20).to({startPosition:0},38).to({y:-150},12).to({_off:true},53).wait(286));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(100,150,200,300);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;